/* CREATE CICLI */
CREATE TABLE CICLI(
	ID NUMBER(10) NOT NULL,
	IDDISPOSITIVO NUMBER(10) NULL,
	DATAESAME VARCHAR2(14) NULL,
	IDOPERATOREESAME NUMBER(10) NULL,
	IDESAME NUMBER(10) NULL,
    IDSEDEESAME NUMBER(10) NULL,
    IDUOESAME NUMBER(10) NULL,
    TIPOESAME VARCHAR2(255) NULL,
	IDPAZIENTE VARCHAR2(50) NULL,
	SALA VARCHAR2(255) NULL,
	DATACONSEGNA VARCHAR2(14) NULL,
	IDOPERATORECONSEGNA NUMBER(10) NULL,
	DATATESTTENUTA VARCHAR2(14) NULL,
	IDOPERATORETESTTENUTA NUMBER(10) NULL,
	DATAINIZIOSTERILIZZAZIONE VARCHAR2(14) NULL,
	IDOPERATOREINIZIOSTERILIZZAZIO NUMBER(10) NULL,
	DATAFINESTERILIZZAZIONE VARCHAR2(14) NULL,
	IDOPERATOREFINESTERILIZZAZIONE NUMBER(10) NULL,
	IDSTERILIZZATRICE NUMBER(10) NULL,
	DATAARMADIO VARCHAR2(14) NULL,
	IDOPERATOREARMADIO NUMBER(10) NULL,
	DATAPRELAVAGGIO VARCHAR2(14) NULL,
	IDOPERATOREPRELAVAGGIO NUMBER(10) NULL,
	IDVASCA VARCHAR2(14) NULL,
	MACHINECYCLEID VARCHAR2(50) NULL,
	DISINFECTANTCYCLEID VARCHAR2(50) NULL,
	FAILED NUMBER(1) DEFAULT(0) NOT NULL,
	MODIFICAMANUALE NUMBER(1) DEFAULT(0) NOT NULL,
 CONSTRAINT PK_CICLI PRIMARY KEY (ID));

CREATE SEQUENCE SEQ_CICLI
    START WITH 1
    MAXVALUE 1000000000000000000000000000
    MINVALUE 1
    NOCYCLE
    NOCACHE
    ORDER;

CREATE OR REPLACE TRIGGER TRG_CICLI
    BEFORE INSERT ON CICLI FOR EACH ROW
    BEGIN
        SELECT SEQ_CICLI.NEXTVAL INTO :NEW.ID FROM DUAL;
    END;
/

/* CREATE TIPIDISPOSITIVI */
CREATE TABLE TIPIDISPOSITIVI(
    ID NUMBER(10) NOT NULL, 
    DESCRIZIONE VARCHAR2(255) NULL,
    CONSTRAINT PK_TIPIDISPOSITIVI PRIMARY KEY(ID)); 

CREATE SEQUENCE SEQ_TIPIDISPOSITIVI
    START WITH 1
    MAXVALUE 1000000000000000000000000000
    MINVALUE 1
    NOCYCLE
    NOCACHE
    ORDER;

CREATE OR REPLACE TRIGGER TRG_TIPIDISPOSITIVI
    BEFORE INSERT ON TIPIDISPOSITIVI FOR EACH ROW
    BEGIN
        SELECT SEQ_TIPIDISPOSITIVI.NEXTVAL INTO :NEW.ID FROM DUAL;
    END;
    /

/* CREATE FORNITORI */
CREATE TABLE FORNITORI(
    ID NUMBER(10) NOT NULL,
    MATRICOLA VARCHAR2(50) NULL,
    DESCRIZIONE VARCHAR2(255) NULL,
    CONSTRAINT PK_FORNITORI PRIMARY KEY(ID));

CREATE SEQUENCE SEQ_FORNITORI
    START WITH 1
    MAXVALUE 1000000000000000000000000000
    MINVALUE 1
    NOCYCLE
    NOCACHE
    ORDER;

CREATE OR REPLACE TRIGGER TRG_FORNITORI
    BEFORE INSERT ON FORNITORI FOR EACH ROW
    BEGIN
        SELECT SEQ_FORNITORI.NEXTVAL INTO :NEW.ID FROM DUAL;
    END;
    /

/* CREATE DISPOSITIVI */
CREATE TABLE DISPOSITIVI(
    ID NUMBER(10) NOT NULL,
    MATRICOLA VARCHAR2(50) NULL,
	SERIALE VARCHAR2(255) NULL,
	DESCRIZIONE VARCHAR2(255) NULL,
	IDTIPO NUMBER(10) NULL,
	IDFORNITORE NUMBER(10) NULL,
	STATO NUMBER(10) NULL,
	ESAMIESEGUITI NUMBER(10) DEFAULT(0) NOT NULL,
	DATAINIZIO VARCHAR2(14) NULL,
	DATAFINE VARCHAR2(14) NULL,
	DISMESSO NUMBER(1) DEFAULT(0) NOT NULL,
	IDCAUSALEDISMISSIONE NUMBER(10) NULL,
	IDRFID1 NUMBER(10) NULL,
	IDRFID2 NUMBER(10) NULL,
	TAG VARCHAR2(50) NULL,
	IDSEDE NUMBER(10) NOT NULL,
	ELIMINATO NUMBER(1) DEFAULT(0) NOT NULL,
	DATASTATO VARCHAR2(14) NULL,
	IDOPERATORESTATO NUMBER(10) NULL,
    CONSTRAINT PK_DISPOSITIVI PRIMARY KEY(ID));

CREATE SEQUENCE SEQ_DISPOSITIVI
    START WITH 1
    MAXVALUE 1000000000000000000000000000
    MINVALUE 1
    NOCYCLE
    NOCACHE
    ORDER;

CREATE TRIGGER TRG_DISPOSITIVI
    BEFORE INSERT ON DISPOSITIVI FOR EACH ROW
    BEGIN
        SELECT SEQ_DISPOSITIVI.NEXTVAL INTO :NEW.ID FROM DUAL;
    END;
    /

/* CREATE STATO */
CREATE TABLE STATO(
	ID NUMBER(10) NOT NULL,
	DESCRIZIONE VARCHAR2(255) NOT NULL,
	DESCRIZIONEAZIONE VARCHAR2(255) NULL,
	BARCODE VARCHAR2(255) NULL,
	COLORE NUMBER(10) DEFAULT (0) NOT NULL,
	ELIMINATO NUMBER(1) DEFAULT (0) NOT NULL,
	VISIBILEMENU NUMBER(10) DEFAULT (0) NOT NULL,
	VISIBILELISTA NUMBER(10) DEFAULT (0) NOT NULL,
	INIZIOCICLO NUMBER(1) DEFAULT (0) NOT NULL,
	INIZIOSTERILIZZAZIONE NUMBER(1) DEFAULT (0) NOT NULL,
	FINESTERILIZZAZIONE NUMBER(1) DEFAULT (0) NOT NULL,
	INIZIOSTOCCAGGIO NUMBER(1) DEFAULT (0) NOT NULL,
	FINESTOCCAGGIO NUMBER(1) DEFAULT (0) NOT NULL,
	VISIBILELISTADETTAGLIO NUMBER(10) DEFAULT (0) NOT NULL,
	SCELTARAPIDA VARCHAR2(50) NULL,
	VISIBILEPRINCIPALE NUMBER(10) DEFAULT (0) NOT NULL,
    INIZIOPRELAVAGGIO NUMBER(1,0) DEFAULT(0) NOT NULL,
    FINEPRELAVAGGIO NUMBER(1,0) DEFAULT(0) NOT NULL,
    CONSTRAINT PK_STATO PRIMARY KEY(ID));

CREATE SEQUENCE SEQ_STATO
    START WITH 1
    MAXVALUE 1000000000000000000000000000
    MINVALUE 1
    NOCYCLE
    NOCACHE
    ORDER;

CREATE TRIGGER TRG_STATO
    BEFORE INSERT ON STATO FOR EACH ROW
    BEGIN
        SELECT SEQ_STATO.NEXTVAL INTO :NEW.ID FROM DUAL;
    END;
    /

/* CREATE VISTADISPOSITIVI */
CREATE OR REPLACE VIEW VISTADISPOSITIVI
AS
SELECT DISPOSITIVI.ID, DISPOSITIVI.MATRICOLA, DISPOSITIVI.DESCRIZIONE, DISPOSITIVI.ESAMIESEGUITI,
    (SELECT COUNT(*) AS EXPR1 FROM CICLI WHERE (IDDISPOSITIVO = DISPOSITIVI.ID)) AS CICLIESEGUITI, 
    DISPOSITIVI.IDFORNITORE, 
    FORNITORI.DESCRIZIONE AS FORNITORE, 
    DISPOSITIVI.IDTIPO, 
    TIPIDISPOSITIVI.DESCRIZIONE AS TIPODISPOSITIVO, 
    STATO.ID AS IDSTATO, 
    STATO.DESCRIZIONE AS STATO, DISPOSITIVI.DISMESSO, 
    DISPOSITIVI.IDSEDE
FROM DISPOSITIVI INNER JOIN STATO ON DISPOSITIVI.STATO = STATO.ID 
LEFT OUTER JOIN FORNITORI ON DISPOSITIVI.IDFORNITORE = FORNITORI.ID 
LEFT OUTER JOIN TIPIDISPOSITIVI ON DISPOSITIVI.IDTIPO = TIPIDISPOSITIVI.ID
WHERE (DISPOSITIVI.ELIMINATO = 0);

/* CREATE CICLISTATOLOG */
CREATE TABLE CICLISTATOLOG(
	ID NUMBER(10) NOT NULL,
	IDCICLO NUMBER(10) NOT NULL,
	IDSTATOOLD NUMBER(10) NOT NULL,
	IDSTATONEW NUMBER(10) NOT NULL,
	IDOPERATORE NUMBER(10) NOT NULL,
	DATAORA VARCHAR2(14) NOT NULL,
 CONSTRAINT PK_CICLISTATOLOG PRIMARY KEY(ID));

 CREATE SEQUENCE SEQ_CICLISTATOLOG
    START WITH 1
    MAXVALUE 1000000000000000000000000000
    MINVALUE 1
    NOCYCLE
    NOCACHE
    ORDER;

CREATE TRIGGER TRG_CICLISTATOLOG
    BEFORE INSERT ON CICLISTATOLOG FOR EACH ROW
    BEGIN
        SELECT SEQ_CICLISTATOLOG.NEXTVAL INTO :NEW.ID FROM DUAL;
    END;
    /

/* CREATE VISTADISPOSITIVIULTIMOCICLO */
CREATE OR REPLACE VIEW VISTADISPOSITIVIULTIMOCICLO
AS
SELECT VISTADISPOSITIVI.ID, MATRICOLA, VISTADISPOSITIVI.DESCRIZIONE, IDSTATO, STATO, IDFORNITORE, IDTIPO, DISMESSO, IDSEDE,
       (SELECT COUNT(*) FROM CICLI WHERE (IDDISPOSITIVO = VISTADISPOSITIVI.ID)) AS CICLIESEGUITI, 
       A.IDSTATOOLD, A.IDSTATONEW, A.IDOPERATORE, A.DATAORA
FROM VISTADISPOSITIVI
     LEFT OUTER JOIN (SELECT MAX(ID) AS MAXCICLO, IDDISPOSITIVO FROM CICLI GROUP BY IDDISPOSITIVO) B ON B.IDDISPOSITIVO = VISTADISPOSITIVI.ID
     LEFT OUTER JOIN (SELECT IDCICLO, IDSTATOOLD, IDSTATONEW, IDOPERATORE, DATAORA 
                      FROM CICLISTATOLOG
                           INNER JOIN STATO ON CICLISTATOLOG.IDSTATONEW = STATO.ID 
                      WHERE STATO.VISIBILELISTA > 0) A ON A.IDCICLO = B.MAXCICLO;

/* CREATE OPERATORI */
CREATE TABLE OPERATORI (
    ID NUMBER(10) NOT NULL,
    MATRICOLA VARCHAR2(50) NULL,
    COGNOME VARCHAR2(50) NULL,
    NOME VARCHAR2(50) NULL,
    DISATTIVATO NUMBER(1) DEFAULT(0) NOT NULL,
    ID_UTENTE NUMBER(10) NULL,
    IDRFID1 NUMBER(10) NULL,
    IDRFID2 NUMBER(10) NULL,
    TAG VARCHAR2(50) NULL,
    CONSTRAINT PK_OPERATORI PRIMARY KEY(ID));

CREATE SEQUENCE SEQ_OPERATORI
    START WITH 1
    MAXVALUE 1000000000000000000000000000
    MINVALUE 1
    NOCYCLE
    NOCACHE
    ORDER;

CREATE TRIGGER TRG_OPERATORI
    BEFORE INSERT ON OPERATORI FOR EACH ROW
    BEGIN
        SELECT SEQ_OPERATORI.NEXTVAL INTO :NEW.ID FROM DUAL;
    END;
    /

/* CREATE VISTADISPOSITIVICICLI */
CREATE VIEW VISTADISPOSITIVICICLI
AS
SELECT VISTADISPOSITIVI.ID, CICLI.ID AS IDCICLO, CICLI.IDPAZIENTE, CICLI.IDESAME, CICLI.SALA,
	   CICLISTATOLOG.IDSTATOOLD, CICLISTATOLOG.IDSTATONEW, 
	   CICLISTATOLOG.DATAORA, CICLISTATOLOG.IDOPERATORE, OPERATORI.COGNOME, OPERATORI.NOME
FROM VISTADISPOSITIVI
	 INNER JOIN CICLI ON VISTADISPOSITIVI.ID = CICLI.IDDISPOSITIVO
	 LEFT OUTER JOIN CICLISTATOLOG ON CICLISTATOLOG.IDCICLO = CICLI.ID
	 LEFT OUTER JOIN OPERATORI ON OPERATORI.ID = CICLISTATOLOG.IDOPERATORE;

/* CREATE CLEANTRACK_DISPOSITIVI */
CREATE VIEW CLEANTRACK_DISPOSITIVI AS
SELECT ID, MATRICOLA, IDRFID1, IDRFID2, DESCRIZIONE, STATO, ESAMIESEGUITI, DISMESSO, DATAINIZIO
FROM DISPOSITIVI;

/* CREATE MAIL */
CREATE TABLE MAIL(
    ID NUMBER(10) NOT NULL,
    NOME VARCHAR2(50) NULL,
    COGNOME VARCHAR2(50) NULL,
    MAIL VARCHAR2(50) NOT NULL,
    ELIMINATO NUMBER(1) DEFAULT(0) NOT NULL,
    CONSTRAINT PK_MAIL PRIMARY KEY(ID));

CREATE SEQUENCE SEQ_MAIL
    START WITH 1
    MAXVALUE 1000000000000000000000000000
    MINVALUE 1
    NOCYCLE
    NOCACHE
    ORDER;

CREATE TRIGGER TRG_MAIL 
    BEFORE INSERT ON MAIL FOR EACH ROW
    BEGIN
        SELECT SEQ_MAIL.NEXTVAL INTO :NEW.ID FROM DUAL;
    END;
    /

/* CREATE CLEANTRACK_MAIL */
CREATE VIEW CLEANTRACK_MAIL AS
SELECT MAIL, ELIMINATO, ID
FROM MAIL;

/* CREATE CLEANTRACK_OPERATORI */
CREATE VIEW CLEANTRACK_OPERATORI AS
SELECT ID, MATRICOLA, IDRFID1, IDRFID2, COGNOME, NOME, DISATTIVATO
FROM OPERATORI;

/* CREATE TIPIDISPOSITIVISTATOSCADENZA */
CREATE TABLE TIPIDISPOSITIVISTATOSCADENZA(
    ID NUMBER(10) NOT NULL,
    IDTIPODISPOSITIVO NUMBER(10) NOT NULL,
	IDSTATO NUMBER(10) NOT NULL,
	SCADENZAMINUTI NUMBER(10) NOT NULL,
	IDSTATODESTINAZIONE NUMBER(10) NOT NULL,
	ELIMINATO NUMBER(1) DEFAULT(0) NOT NULL,
    CONSTRAINT PK_TDISPSTATOSCADENZA PRIMARY KEY(ID));

CREATE SEQUENCE SEQ_TIPIDISPSTATOSCADENZA
    START WITH 1
    MAXVALUE 1000000000000000000000000000
    MINVALUE 1
    NOCYCLE
    NOCACHE
    ORDER;

CREATE TRIGGER TRG_TIPIDISPSTATOSCADENZA
    BEFORE INSERT ON TIPIDISPOSITIVISTATOSCADENZA FOR EACH ROW
    BEGIN
        SELECT SEQ_TIPIDISPSTATOSCADENZA.NEXTVAL INTO :NEW.ID FROM DUAL;
    END;
    /

/* CREATE VISTADISPOSITIVISCADUTI */
CREATE OR REPLACE VIEW "CLEANTRACK"."VISTADISPOSITIVISCADUTI" ("ID", "STATO", "IDSTATODESTINAZIONE", "IDOPERATORESTATO") AS 
SELECT DISPOSITIVI.ID, DISPOSITIVI.STATO, TIPIDISPOSITIVISTATOSCADENZA.IDSTATODESTINAZIONE, DISPOSITIVI.IDOPERATORESTATO
FROM DISPOSITIVI 
     INNER JOIN TIPIDISPOSITIVISTATOSCADENZA ON DISPOSITIVI.IDTIPO = TIPIDISPOSITIVISTATOSCADENZA.IDTIPODISPOSITIVO AND DISPOSITIVI.STATO = TIPIDISPOSITIVISTATOSCADENZA.IDSTATO 
WHERE (CURRENT_DATE - TO_DATE(DISPOSITIVI.DATASTATO, 'YYYYMMDDHH24MISS')) * 24 * 60 > TIPIDISPOSITIVISTATOSCADENZA.SCADENZAMINUTI
AND DISPOSITIVI.ELIMINATO = 0 AND DISPOSITIVI.DISMESSO = 0;
/

/* CREATE AM_GETSERVERDATE */
CREATE OR REPLACE VIEW AM_GETSERVERDATE
AS 
SELECT TO_CHAR (CURRENT_DATE, 'YYYYMMDDHH24MISS') AS DATA FROM DUAL;

/* CREATE ARMADI_LAVATRICI */
CREATE TABLE ARMADI_LAVATRICI(
	ID NUMBER(10) NOT NULL,
	MATRICOLA VARCHAR2(50) NULL,
	DESCRIZIONE VARCHAR2(255) NULL,
	SERIALE VARCHAR2(50) NULL,
	DISMESSO NUMBER(1) DEFAULT(0) NULL,
	IDCAUSALEDISMISSIONE NUMBER(10) NULL,
	DATAFINE VARCHAR2(50) NULL,
	TEMPOLAVAGGIO NUMBER(10) NULL,
	IDSEDE NUMBER(10) NOT NULL,
	TIPO NUMBER(10) DEFAULT(0) NOT NULL,
	PERCORSO VARCHAR2(255) NULL,
	POLLINGTIME NUMBER(10) DEFAULT(0) NOT NULL,
    CONSTRAINT PK_ARMADI_LAVATRICI PRIMARY KEY(ID));

CREATE SEQUENCE SEQ_ARMADI_LAVATRICI 
    START WITH 1
    MAXVALUE 1000000000000000000000000000
    MINVALUE 1
    NOCYCLE
    NOCACHE
    ORDER;

CREATE TRIGGER TRG_ARMADI_LAVATRICI
    BEFORE INSERT ON ARMADI_LAVATRICI FOR EACH ROW
    BEGIN
        SELECT SEQ_ARMADI_LAVATRICI.NEXTVAL INTO :NEW.ID FROM DUAL;
    END;
    /

/* CREATE CAUSALI */
CREATE TABLE CAUSALI (
    ID NUMBER(10) NOT NULL,
    CAUSALE VARCHAR2(255) NULL,
    CONSTRAINT PK_CAUSALI PRIMARY KEY(ID));

CREATE SEQUENCE SEQ_CAUSALI
    START WITH 1
    MAXVALUE 1000000000000000000000000000
    MINVALUE 1
    NOCYCLE
    NOCACHE
    ORDER;

CREATE TRIGGER TRG_CAUSALI 
    BEFORE INSERT ON CAUSALI FOR EACH ROW
    BEGIN
        SELECT SEQ_CAUSALI.NEXTVAL INTO :NEW.ID FROM DUAL;
    END;
    /

/* CREATE CICLIEXT */
CREATE TABLE CICLIEXT(
    ID NUMBER(10) NOT NULL,
    IDCICLO NUMBER(10) NULL,
    DESCRIZIONE VARCHAR2(50) NULL,
    VALORE VARCHAR2(255) NULL,
    DATA VARCHAR2(14) NULL,
    ERROR NUMBER(1) DEFAULT(0) NOT NULL,
    CONSTRAINT PK_CICLIEXT PRIMARY KEY (ID));

CREATE SEQUENCE SEQ_CICLIEXT
    START WITH 1
    MAXVALUE 1000000000000000000000000000
    MINVALUE 1
    NOCYCLE
    NOCACHE
    ORDER;

CREATE TRIGGER TRG_CICLIEXT
    BEFORE INSERT ON CICLIEXT FOR EACH ROW
    BEGIN
        SELECT SEQ_CICLIEXT.NEXTVAL INTO :NEW.ID FROM DUAL;
    END;
    /

/* CREATE CONFIGURAZIONE */
CREATE TABLE CONFIGURAZIONE(
    CHIAVE VARCHAR2(50) NOT NULL,
    VALORE VARCHAR2(4000) NULL,
    CONSTRAINT PK_CONFIGURAZIONE PRIMARY KEY(CHIAVE));

/* CREATE GRUPPI */
CREATE TABLE GRUPPI(
    ID NUMBER(10) NOT NULL,
    NOME VARCHAR2(50) NULL,
    DESCRIZIONE VARCHAR2(50) NULL,
    PERMESSI NUMBER(10) DEFAULT(0) NULL,
    PERMESSI2 NUMBER(10) DEFAULT(0) NULL,
    ELIMINATO NUMBER(1) DEFAULT(0) NOT NULL,
    CONSTRAINT PK_GRUPPI PRIMARY KEY (ID));

CREATE SEQUENCE SEQ_GRUPPI
    START WITH 1
    MAXVALUE 1000000000000000000000000000
    MINVALUE 1
    NOCYCLE
    NOCACHE
    ORDER;

CREATE TRIGGER TRG_GRUPPI
    BEFORE INSERT ON GRUPPI FOR EACH ROW
    BEGIN
        SELECT SEQ_GRUPPI.NEXTVAL INTO :NEW.ID FROM DUAL;
    END;
    /

/* CREATE LETTORI */
CREATE TABLE LETTORI(
    ID NUMBER(10) NOT NULL,
    DESCRIZIONE VARCHAR2(255) NOT NULL,
    IP VARCHAR2(50) NOT NULL,
    PORTA NUMBER(10) NOT NULL,
    IDSTATODEFAULT NUMBER(10) NULL,
    TIPO NUMBER(10) DEFAULT(0) NOT NULL,
    ELIMINATO NUMBER(1) DEFAULT(0) NOT NULL,
    ETICHETTAOPERAZIONE VARCHAR2(50) NULL,
    ETICHETTADISPOSITIVO VARCHAR2(50) NULL,
    ETICHETTAOPERATORE VARCHAR2(50) NULL,
    TIMEOUTCOMPLETAMENTOSTEP NUMBER(10) NULL,
    SELEZIONEWORKLIST NUMBER(1) DEFAULT(0) NOT NULL,
    ATTESAPRIMAAPPLICA NUMBER(10) NULL,
    ATTESAPRIMACHIUSURAPOPUP NUMBER(10) DEFAULT(0) NOT NULL,
    IDSEDE NUMBER(10) NOT NULL,
    CONSTRAINT PK_LETTORI PRIMARY KEY (ID));

CREATE SEQUENCE SEQ_LETTORI
    START WITH 1
    MAXVALUE 1000000000000000000000000000
    MINVALUE 1
    NOCYCLE
    NOCACHE
    ORDER;

CREATE TRIGGER TRG_LETTORI
    BEFORE INSERT ON LETTORI FOR EACH ROW
    BEGIN
        SELECT SEQ_LETTORI.NEXTVAL INTO :NEW.ID FROM DUAL;
    END;
    /

/* CREATE LOG */
CREATE TABLE LOG(
	ID NUMBER(10) NOT NULL,
	UTENTE VARCHAR2(50) NULL,
	TABELLA VARCHAR2(50) NULL,
	OPERAZIONE VARCHAR2(50) NULL,
	DATA VARCHAR2(14) NULL,
	RECORD NUMBER(10) NULL,
	CLASSEELEMENTO VARCHAR2(100) NULL,
	NOMECAMPO VARCHAR2(100) NULL,
	VALOREORIGINALE VARCHAR2(255) NULL,
	VALOREMODIFICATO VARCHAR2(255) NULL,
    CONSTRAINT PK_LOG PRIMARY KEY (ID));

CREATE SEQUENCE SEQ_LOG
    START WITH 1
    MAXVALUE 1000000000000000000000000000
    MINVALUE 1
    NOCYCLE
    NOCACHE
    ORDER;

CREATE TRIGGER TRG_LOG
    BEFORE INSERT ON LOG FOR EACH ROW
    BEGIN
        SELECT SEQ_LOG.NEXTVAL INTO :NEW.ID FROM DUAL;
    END;
    /

/* CREATE LOGEXT */
CREATE TABLE LOGEXT(
	ID NUMBER(10) NOT NULL,
	DATEEVENT VARCHAR2(14) NOT NULL,
	CURRENTHOST VARCHAR2(255) NOT NULL,
	MODULENAME VARCHAR2(255) NOT NULL,
	CALLERHOST VARCHAR2(255) NULL,
	ORIGIN VARCHAR2(255) NOT NULL,
	LOGLEVEL VARCHAR2(255) NOT NULL,
	DESCRIPTION VARCHAR2(1024) NULL,
	ATTACHMENT CLOB NULL,
    CONSTRAINT PK_LOGEXT PRIMARY KEY (ID));

CREATE SEQUENCE SEQ_LOGEXT
    START WITH 1
    MAXVALUE 1000000000000000000000000000
    MINVALUE 1
    NOCYCLE
    NOCACHE
    ORDER;

CREATE TRIGGER TRG_LOGEXT
    BEFORE INSERT ON LOGEXT FOR EACH ROW
    BEGIN
        SELECT SEQ_LOGEXT.NEXTVAL INTO :NEW.ID FROM DUAL;
    END;
    /

/* CREATE OPERATORI_SEDI */
CREATE TABLE OPERATORI_SEDI(
	IDOPERATORE NUMBER(10) NOT NULL,
	IDSEDE NUMBER(10) NOT NULL,
    CONSTRAINT PK_OPERATORI_SEDI PRIMARY KEY (IDOPERATORE, IDSEDE));


/* CREATE SEDIESAME */
CREATE TABLE SEDIESAME(
	ID NUMBER(10) NOT NULL,
	DESCRIZIONE VARCHAR2(255) NULL,
	ELIMINATO NUMBER(1) DEFAULT(0) NOT NULL,
    CONSTRAINT PK_SEDIESAME PRIMARY KEY (ID));

/* CREATE STATOCAMBIO */
CREATE TABLE STATOCAMBIO(
	ID NUMBER(10) NOT NULL,
	IDSTATOOLD NUMBER(10) NOT NULL,
	IDSTATONEW NUMBER(10) NOT NULL,
	IDSEDE NUMBER(10) NOT NULL,
	ELIMINATO NUMBER(1) DEFAULT (0) NOT NULL,
    CONSTRAINT PK_STATOCAMBIO PRIMARY KEY (ID));

CREATE SEQUENCE SEQ_STATOCAMBIO
    START WITH 1
    MAXVALUE 1000000000000000000000000000
    MINVALUE 1
    NOCYCLE
    NOCACHE
    ORDER;

CREATE TRIGGER TRG_STATOCAMBIO
    BEFORE INSERT ON STATOCAMBIO FOR EACH ROW
    BEGIN
        SELECT SEQ_STATOCAMBIO.NEXTVAL INTO :NEW.ID FROM DUAL;
    END;
    /

/* CREATE STERILIZZATRICIPARSING */
CREATE TABLE STERILIZZATRICIPARSING(
	ID NUMBER(10) NOT NULL,
	IDSTERILIZZATRICE NUMBER(10) NOT NULL,
	DATAPARSING VARCHAR2(14) NOT NULL,
	FILENAMEDATA VARCHAR2(14) NOT NULL,
	FILENAME VARCHAR2(255) NULL,
	CONTENUTOFILE CLOB NULL,
	CICLOCOMPLETO NUMBER(1) DEFAULT (0) NOT NULL,
	ERROREIMPORT NUMBER(10) DEFAULT (0) NOT NULL,
	IDDISPOSITIVO NUMBER(10) NULL,
	DATAORASTART VARCHAR2(14) NULL,
	IDOPERATORESTART NUMBER(10) NULL,
	DATAORAEND VARCHAR2(14) NULL,
	IDOPERATOREEND NUMBER(10) NULL,
	DATASTATODISPOSITIVO VARCHAR2(14) NULL,
	STATODISPOSITIVO NUMBER(10) NULL,
    CONSTRAINT PK_STERILIZZATRICIPARSING PRIMARY KEY (ID));

CREATE SEQUENCE SEQ_STERILIZZATRICIPARSING
    START WITH 1
    MAXVALUE 1000000000000000000000000000
    MINVALUE 1
    NOCYCLE
    NOCACHE
    ORDER;

CREATE TRIGGER TRG_STERILIZZATRICIPARSING
    BEFORE INSERT ON STERILIZZATRICIPARSING FOR EACH ROW
    BEGIN
        SELECT SEQ_STERILIZZATRICIPARSING.NEXTVAL INTO :NEW.ID FROM DUAL;
    END;
    /

/* CREATE STORICODISMISSIONE */
CREATE TABLE STORICODISMISSIONE(
	ID NUMBER(10) NOT NULL,
	DISMISSIONE NUMBER(10) NOT NULL,
	DATA VARCHAR2(14) NULL,
	CAUSALE VARCHAR2(255) NULL,
	UTENTE VARCHAR2(50) NOT NULL,
	IDDISPOSITIVO NUMBER(10) NOT NULL,
	ELIMINATO NUMBER(10) NOT NULL,
    CONSTRAINT PK_STORICODISMISSIONE PRIMARY KEY (ID));

CREATE SEQUENCE SEQ_STORICODISMISSIONE
    START WITH 1
    MAXVALUE 1000000000000000000000000000
    MINVALUE 1
    NOCYCLE
    NOCACHE
    ORDER;

CREATE TRIGGER TRG_STORICODISMISSIONE
    BEFORE INSERT ON STORICODISMISSIONE FOR EACH ROW
    BEGIN
        SELECT SEQ_STORICODISMISSIONE.NEXTVAL INTO :NEW.ID FROM DUAL;
    END;
    /

/* CREATE UO */
CREATE TABLE UO(
	ID NUMBER(10) NOT NULL,
	DESCRIZIONE VARCHAR2(50) NOT NULL,
	ELIMINATO NUMBER(1) DEFAULT (0) NOT NULL,
    CONSTRAINT PK_UO PRIMARY KEY (ID));

/* CREATE UO_SEDI */
CREATE TABLE UO_SEDI(
	IDUO NUMBER(10) NOT NULL,
	IDSEDE NUMBER(10) NOT NULL,
    CONSTRAINT PK_UO_SEDI PRIMARY KEY (IDUO, IDSEDE));

/* CREATE UTENTI */
CREATE TABLE UTENTI(
	ID NUMBER(10) NOT NULL,
	USERNAME VARCHAR2(50) NULL,
	PASSWORD VARCHAR2(50) NULL,
	ID_GRUPPO NUMBER(10) DEFAULT (0) NOT NULL,
	DISABILITATO NUMBER(1) DEFAULT (0) NOT NULL,
	SCADENZA_PASSWORD NUMBER(10) DEFAULT (365) NOT NULL,
	DATA_PASSWORD VARCHAR2(14) DEFAULT (20081209000000.) NOT NULL,
	DATA_ULTIMO_UTILIZZO VARCHAR2(14) DEFAULT (20081209000000.) NOT NULL,
	PRIMO_LOGIN NUMBER(1) DEFAULT (0) NOT NULL,
	DESCRIZIONE VARCHAR2(255) NULL,
	TIPO_PASSWORD NUMBER(10) DEFAULT (0) NOT NULL,
	ELIMINATO NUMBER(1) DEFAULT (0) NOT NULL,
	CODICEINTEGRAZIONE VARCHAR2(255) NULL,
    CONSTRAINT PK_UTENTI PRIMARY KEY (ID));

CREATE SEQUENCE SEQ_UTENTI
    START WITH 1
    MAXVALUE 1000000000000000000000000000
    MINVALUE 1
    NOCYCLE
    NOCACHE
    ORDER;

CREATE TRIGGER TRG_UTENTI
    BEFORE INSERT ON UTENTI FOR EACH ROW
    BEGIN
        SELECT SEQ_UTENTI.NEXTVAL INTO :NEW.ID FROM DUAL;
    END;
    /

/* CREATE UTENTI_LOG */
CREATE TABLE UTENTI_LOG(
	ID NUMBER(10) NOT NULL,
	USERNAME VARCHAR2(50) NOT NULL,
	EVENTO NUMBER(10) NOT NULL,
	DATA VARCHAR2(14) NOT NULL,
    CONSTRAINT PK_UTENTI_LOG PRIMARY KEY (ID));

CREATE SEQUENCE SEQ_UTENTI_LOG
    START WITH 1
    MAXVALUE 1000000000000000000000000000
    MINVALUE 1
    NOCYCLE
    NOCACHE
    ORDER;

CREATE TRIGGER TRG_UTENTI_LOG
    BEFORE INSERT ON UTENTI_LOG FOR EACH ROW
    BEGIN
        SELECT SEQ_UTENTI_LOG.NEXTVAL INTO :NEW.ID FROM DUAL;
    END;
    /

/* CREATE UTENTI_SETTING */
CREATE TABLE UTENTI_SETTING(
	ID NUMBER(10) NOT NULL,
	IDUTENTE NUMBER(10) NOT NULL,
	CHIAVE VARCHAR2(50) NOT NULL,
	VALORE VARCHAR2(255) NULL,
    CONSTRAINT PK_UTENTI_SETTING PRIMARY KEY (ID));

CREATE SEQUENCE SEQ_UTENTI_SETTING
    START WITH 1
    MAXVALUE 1000000000000000000000000000
    MINVALUE 1
    NOCYCLE
    NOCACHE
    ORDER;

CREATE TRIGGER TRG_UTENTI_SETTING
    BEFORE INSERT ON UTENTI_SETTING FOR EACH ROW
    BEGIN
        SELECT SEQ_UTENTI_SETTING.NEXTVAL INTO :NEW.ID FROM DUAL;
    END;
    /

CREATE TABLE CONFIGURAZIONIAMLOGIN (
    ID NUMBER(10,0) NOT NULL,
    VOCE VARCHAR(255),
    VALORE VARCHAR(255),
    IDUO NUMBER(10,0) DEFAULT 0 NOT NULL,
    ELIMINATO NUMBER(1) DEFAULT (0) NOT NULL,
CONSTRAINT PK_CONFIGURAZIONIAMLOGIN PRIMARY KEY (ID)
)
/
CREATE SEQUENCE SEQ_CONF_AMLOGIN
    START WITH 1
    MAXVALUE 1000000000000000000000000000
    MINVALUE 1
    NOCYCLE
    NOCACHE
    ORDER;
/
CREATE OR REPLACE TRIGGER TRG_CONF_AMLOGIN
    BEFORE INSERT ON CONFIGURAZIONIAMLOGIN FOR EACH ROW
    BEGIN
        SELECT SEQ_CONF_AMLOGIN.NEXTVAL INTO :NEW.ID FROM DUAL;
    END;
/

CREATE TABLE UTENTI_PASSWORDS
(
       ID NUMBER(10, 0) NOT NULL,
       IDUTENTE NUMBER(10, 0),
       DATAORA VARCHAR(14),
       PASSWORD VARCHAR(4000),
       ELIMINATO NUMBER(1) DEFAULT (0) NOT NULL,
CONSTRAINT PK_UTENTI_PASSWORDS PRIMARY KEY (ID)
)
/
CREATE SEQUENCE SEQ_UTENTI_PWD
    START WITH 1
    MAXVALUE 1000000000000000000000000000
    MINVALUE 1
    NOCYCLE
    NOCACHE
    ORDER;
/
CREATE OR REPLACE TRIGGER TRG_UTENTI_PWD
    BEFORE INSERT ON UTENTI_PASSWORDS FOR EACH ROW
    BEGIN
        SELECT SEQ_UTENTI_PWD.NEXTVAL INTO :NEW.ID FROM DUAL;
    END;
/

/* FOREIGN KEY */
ALTER TABLE ARMADI_LAVATRICI ADD CONSTRAINT FK_ARMADI_LAVATRICI_SEDIESAME FOREIGN KEY (IDSEDE) REFERENCES SEDIESAME(ID);
ALTER TABLE CICLI ADD CONSTRAINT FK_CICLI_DISPOSITIVI FOREIGN KEY(IDDISPOSITIVO) REFERENCES DISPOSITIVI(ID) ON DELETE CASCADE;
ALTER TABLE CICLI ADD CONSTRAINT FK_CICLI_OPERATORI FOREIGN KEY(IDOPERATOREESAME) REFERENCES OPERATORI(ID) ON DELETE CASCADE;
ALTER TABLE CICLI ADD CONSTRAINT FK_CICLI_STER FOREIGN KEY(IDSTERILIZZATRICE) REFERENCES ARMADI_LAVATRICI(ID) ON DELETE CASCADE;
ALTER TABLE CICLIEXT ADD CONSTRAINT FK_CICLIEXT_CICLI FOREIGN KEY (IDCICLO) REFERENCES CICLI(ID) ON DELETE CASCADE;
ALTER TABLE CICLISTATOLOG ADD CONSTRAINT FK_CICLISTLOG_CICLI FOREIGN KEY (IDCICLO) REFERENCES CICLI(ID) ON DELETE CASCADE;
ALTER TABLE CICLISTATOLOG ADD CONSTRAINT FK_CICLISTLOG_STATONEW FOREIGN KEY (IDSTATONEW) REFERENCES STATO(ID);
ALTER TABLE CICLISTATOLOG ADD CONSTRAINT FK_CICLISTLOG_STATOOLD FOREIGN KEY (IDSTATOOLD) REFERENCES STATO(ID);
ALTER TABLE DISPOSITIVI ADD CONSTRAINT FK_DISP_FORNITORI FOREIGN KEY (IDFORNITORE) REFERENCES FORNITORI(ID);
ALTER TABLE DISPOSITIVI ADD CONSTRAINT FK_DISP_SEDIESAME FOREIGN KEY(IDSEDE) REFERENCES SEDIESAME(ID) ON DELETE CASCADE;
ALTER TABLE DISPOSITIVI ADD CONSTRAINT FK_DISP_TIPIDISP FOREIGN KEY(IDTIPO) REFERENCES TIPIDISPOSITIVI(ID);
ALTER TABLE LETTORI ADD CONSTRAINT FK_LETTORI_SEDIESAME FOREIGN KEY(IDSEDE) REFERENCES SEDIESAME(ID) ON DELETE CASCADE;
ALTER TABLE LETTORI ADD CONSTRAINT FK_LETTORI_STATO FOREIGN KEY(IDSTATODEFAULT) REFERENCES STATO(ID);
ALTER TABLE OPERATORI ADD CONSTRAINT FK_OPERATORI_UTENTI FOREIGN KEY (ID_UTENTE) REFERENCES UTENTI(ID) ON DELETE SET NULL;
ALTER TABLE OPERATORI_SEDI ADD CONSTRAINT FK_OPER_SEDI_OPERATORI FOREIGN KEY (IDOPERATORE) REFERENCES OPERATORI(ID) ON DELETE CASCADE;
ALTER TABLE OPERATORI_SEDI ADD CONSTRAINT FK_OPER_SEDI_SEDIESAME FOREIGN KEY (IDSEDE) REFERENCES SEDIESAME(ID);
ALTER TABLE STATOCAMBIO ADD CONSTRAINT FK_STATOCAMBIO_SEDIESAME FOREIGN KEY (IDSEDE) REFERENCES SEDIESAME(ID) ON DELETE CASCADE;
ALTER TABLE STATOCAMBIO ADD CONSTRAINT FK_STATOCAMBIO_STATONEW FOREIGN KEY (IDSTATONEW) REFERENCES STATO(ID);
ALTER TABLE STATOCAMBIO ADD CONSTRAINT FK_STATOCAMBIO_STATOOLD FOREIGN KEY (IDSTATOOLD) REFERENCES STATO(ID);
ALTER TABLE STERILIZZATRICIPARSING ADD CONSTRAINT FK_STERPARSING_STER FOREIGN KEY (IDSTERILIZZATRICE) REFERENCES ARMADI_LAVATRICI(ID);
ALTER TABLE TIPIDISPOSITIVISTATOSCADENZA ADD CONSTRAINT FK_TIPIDISPSCAD_ST1 FOREIGN KEY (IDSTATO) REFERENCES STATO(ID);
ALTER TABLE TIPIDISPOSITIVISTATOSCADENZA ADD CONSTRAINT FK_TIPIDISPSCAD_ST2 FOREIGN KEY (IDSTATODESTINAZIONE) REFERENCES STATO(ID);
ALTER TABLE TIPIDISPOSITIVISTATOSCADENZA ADD CONSTRAINT FK_TIPIDISPSCAD_TIPIDISP FOREIGN KEY (IDTIPODISPOSITIVO) REFERENCES TIPIDISPOSITIVI(ID);
ALTER TABLE UO_SEDI ADD CONSTRAINT FK_UO_SEDI_SEDIESAME FOREIGN KEY (IDSEDE) REFERENCES SEDIESAME(ID) ON DELETE CASCADE;
ALTER TABLE UO_SEDI ADD CONSTRAINT FK_UO_SEDI_UO FOREIGN KEY (IDUO) REFERENCES UO(ID) ON DELETE CASCADE;
ALTER TABLE UTENTI ADD CONSTRAINT FK_UTENTI_GRUPPI FOREIGN KEY (ID_GRUPPO) REFERENCES GRUPPI(ID) ON DELETE CASCADE;
ALTER TABLE UTENTI_SETTING ADD CONSTRAINT FK_UTENTI_SETTING_UTENTI FOREIGN KEY (IDUTENTE) REFERENCES UTENTI(ID) ON DELETE CASCADE;

/* STORED PROCEDURE */

CREATE OR REPLACE PROCEDURE SP_INSERTGROUP
(
	nGROUPID OUT NUMBER,
	sUsernameMod varchar2,
	sComputerName varchar2,
	sInstallationName varchar2,
	sGROUPNAME IN VARCHAR2,
	nALLOWEDACTION IN NUMBER,
	nALLOWEDACTION2 IN NUMBER
)
AS
BEGIN
	INSERT INTO GRUPPI (NOME, PERMESSI) VALUES (sGROUPNAME, nALLOWEDACTION);
	SELECT SEQ_GRUPPI.CURRVAL INTO nGROUPID FROM DUAL;
END;
/

CREATE OR REPLACE PROCEDURE SP_INSERTUSER
(
    USERID OUT NUMBER,
    USERNAMEMOD VARCHAR2,
    COMPUTERNAME VARCHAR2,
    INSTALLATIONNAME VARCHAR2,
    USERNAME VARCHAR2,
    FIRSTLOGIN NUMBER,
    DISABLED NUMBER,
    GROUPID NUMBER,
    DATECHANGEPWD VARCHAR2,
    DATELASTUSE VARCHAR2
)
AS 
BEGIN
    INSERT INTO UTENTI 
    (USERNAME, PASSWORD, ID_GRUPPO, DISABILITATO, DATA_PASSWORD, DATA_ULTIMO_UTILIZZO, PRIMO_LOGIN)
    VALUES (USERNAME, '', GROUPID, DISABLED, DATECHANGEPWD, DATELASTUSE, FIRSTLOGIN);
    SELECT SEQ_UTENTI.CURRVAL INTO USERID FROM DUAL;
END;
/


CREATE OR REPLACE PROCEDURE SP_MODIFYGROUP
(
	sUsernameMod varchar,
	sComputerName varchar,
	sInstallationName varchar,
	nGROUPID NUMBER,
	sGROUPNAME VARCHAR,
	nALLOWEDACTION NUMBER,
	nALLOWEDACTION2 NUMBER,
	nDELETED NUMBER
)
AS
BEGIN

	IF (sGROUPNAME IS NOT NULL) THEN
		UPDATE GRUPPI SET NOME = sGROUPNAME WHERE ID = nGROUPID;
	END IF;

	IF (nALLOWEDACTION IS NOT NULL) THEN
  	UPDATE GRUPPI SET PERMESSI = nALLOWEDACTION WHERE ID = nGROUPID;
	END IF;

	IF (nALLOWEDACTION2 IS NOT NULL) THEN
  	UPDATE GRUPPI SET PERMESSI2 = nALLOWEDACTION2 WHERE ID = nGROUPID;
	END IF;

	IF (nDELETED IS NOT NULL) THEN
		UPDATE GRUPPI SET ELIMINATO = nDELETED WHERE ID = nGROUPID;
	END IF;
END;
/

CREATE OR REPLACE PROCEDURE SP_MODIFYUSER
(
	USERNAMEMOD VARCHAR2,
	COMPUTERNAME VARCHAR2,
	INSTALLATIONNAME VARCHAR2,
	USERID NUMBER,
	PUSERNAME VARCHAR2,
	SDESCRIZIONE VARCHAR2,
	SPASSWORD VARCHAR2,
	PASSWORDTYPE NUMBER,
	GROUPID NUMBER,
	DISABLED NUMBER,
	PASSWORDDATE VARCHAR2,
	LASTUSEDATE VARCHAR2,
	FIRSTLOGIN NUMBER,
	DELETED NUMBER,
	CODE VARCHAR2
)
AS
    TRIMMEDPWD VARCHAR2(50);
BEGIN
    IF (PUSERNAME IS NOT NULL) THEN
        UPDATE UTENTI SET USERNAME = PUSERNAME WHERE ID = USERID;
    END IF;

    IF (SDESCRIZIONE IS NOT NULL) THEN
        UPDATE UTENTI SET DESCRIZIONE = SDESCRIZIONE WHERE ID = USERID;
    END IF;

    IF (SPASSWORD IS NOT NULL) THEN
        TRIMMEDPWD := TRIM(SPASSWORD); -- PER COLPA DI ORACLE PASSO UNO SPAZIO QUANDO LA PASSWORD È DA RESETTARE --
        UPDATE UTENTI SET PASSWORD = TRIMMEDPWD WHERE ID = USERID;
    END IF;

    IF (PASSWORDTYPE IS NOT NULL) THEN
        UPDATE UTENTI SET TIPO_PASSWORD = PASSWORDTYPE WHERE ID = USERID;
    END IF;

    IF (GROUPID IS NOT NULL) THEN
        UPDATE UTENTI SET ID_GRUPPO = GROUPID WHERE ID = USERID;
    END IF;

    IF (DISABLED IS NOT NULL) THEN
        UPDATE UTENTI SET DISABILITATO = DISABLED WHERE ID = USERID;
    END IF;

    IF (PASSWORDDATE IS NOT NULL) THEN
        UPDATE UTENTI SET DATA_PASSWORD = PASSWORDDATE WHERE ID = USERID;
    END IF;

    IF (LASTUSEDATE IS NOT NULL) THEN
        UPDATE UTENTI SET DATA_ULTIMO_UTILIZZO = LASTUSEDATE WHERE ID = USERID;
    END IF;

    IF (FIRSTLOGIN IS NOT NULL) THEN
        UPDATE UTENTI SET PRIMO_LOGIN = FIRSTLOGIN WHERE ID = USERID;
    END IF;

    IF (DELETED IS NOT NULL) THEN
        UPDATE UTENTI SET ELIMINATO = DELETED WHERE ID = USERID;
    END IF;

    IF (CODE IS NOT NULL) THEN
        UPDATE UTENTI SET CODICEINTEGRAZIONE = CODE WHERE ID = USERID;
    END IF;
END;
/

CREATE OR REPLACE PROCEDURE SP_UPDATEDEVNEW
(
    nRES OUT NUMBER, 
    sTAGDEVICE VARCHAR2, 
    nSTATE NUMBER, 
    sDATECLEAN VARCHAR2, 
    sTAGUSERCLEAN VARCHAR2, 
    nCLEANER NUMBER, 
    nOLDSTATE NUMBER, 
    nEXAM NUMBER
)
AS
    nCNT NUMBER(10);
    sTEMPDATE VARCHAR2(14);
    nTRACKSTATO NUMBER(10);
    nCNTSTATO NUMBER(10);
    nIDCYCLE NUMBER(10);
    nIDTAG NUMBER(10);
    nIDUSERCLEAN NUMBER(10);
BEGIN
    nRES := -1;
    SELECT COUNT(*) INTO nCNT FROM DISPOSITIVI WHERE TAG=sTAGDEVICE;
    IF (nCNT = 0) THEN
        nRES := -2;
    END IF;
    
    SELECT COUNT(*) INTO nCNT FROM OPERATORI WHERE TAG=sTAGUSERCLEAN;
    IF (nCNT = 0) THEN
        nRES := -3;
    END IF;

    SELECT ID INTO nIDTAG FROM DISPOSITIVI WHERE TAG=sTAGDEVICE;
    SELECT ID INTO nIDUSERCLEAN FROM OPERATORI WHERE TAG=sTAGUSERCLEAN;

    IF (nSTATE = 99999) THEN
        SELECT MAX(ID) INTO nIDCYCLE FROM CICLI WHERE IDDISPOSITIVO = nIDTAG;
        UPDATE Cicli SET FAILED=1 WHERE ID=nIDCYCLE;
        
        INSERT INTO CICLI (IDDispositivo,DataEsame,IDOperatoreEsame,ModificaManuale,IDEsame)
            SELECT IDDispositivo,DataEsame,IDOperatoreEsame,ModificaManuale,IDEsame FROM CICLI WHERE ID=nIDCYCLE;
        
        UPDATE DISPOSITIVI SET STATO = 2 WHERE ID = nIDTAG;
        nRES := nIDCYCLE;
    END IF;
        
    IF (nSTATE = 2) THEN --sporco
        INSERT INTO CICLI (IDDispositivo,DataEsame,IDOperatoreEsame,IDEsame)
            VALUES (nIDTAG,sDATECLEAN,nIDUSERCLEAN,nEXAM);
            
        SELECT MAX(ID) INTO nIDCYCLE FROM CICLI WHERE IDDISPOSITIVO = nIDTAG;

        UPDATE DISPOSITIVI SET STATO = nSTATE WHERE ID = nIDTAG;
        
        INSERT INTO CicliStatoLog (IDCICLO, IDSTATOOLD, IDSTATONEW, IDOPERATORE, DATAORA) 
            VALUES (nIDCYCLE, nOLDSTATE, nSTATE, nIDUSERCLEAN, sDATECLEAN);
            
        nRES := nIDCYCLE;
    END IF;
END;
/
