--UO DI DEFAULT
INSERT INTO UO (ID, DESCRIZIONE) VALUES(1, 'TO_DEFINE');
COMMIT;
--SEDE DI DEFAULT
INSERT INTO SEDIESAME (ID, DESCRIZIONE) VALUES (1, 'TO_DEFINE');
INSERT INTO UO_SEDI (IDUO, IDSEDE) VALUES (1, 1);
COMMIT;

-- VALORI CONFIGURAZIONE
INSERT INTO CONFIGURAZIONE (CHIAVE, VALORE) VALUES ('Attiva trigger compatibilità', '0');
INSERT INTO CONFIGURAZIONE (CHIAVE, VALORE) VALUES ('db_version', '99.99');
INSERT INTO CONFIGURAZIONE (CHIAVE, VALORE) VALUES ('Server Host', 'INSERT_IP_OR_SERVER_NAME');
INSERT INTO CONFIGURAZIONE (CHIAVE, VALORE) VALUES ('Server Port', '8091');
COMMIT;

-- GRUPPI UTENTE
INSERT INTO GRUPPI (NOME, DESCRIZIONE, PERMESSI, PERMESSI2) VALUES ('ADMINISTRATORS', 'ADMINISTRATORS', 1, 0);
INSERT INTO GRUPPI (NOME, DESCRIZIONE, PERMESSI, PERMESSI2) VALUES ('DEFAULT', 'DEFAULT', 0, 0);
COMMIT;

-- STATI DI DEFAULT

-- stato pulito
INSERT INTO STATO (ID, DESCRIZIONE, DESCRIZIONEAZIONE, BARCODE, COLORE, ELIMINATO, VISIBILEMENU, VISIBILELISTA, INIZIOCICLO, INIZIOSTERILIZZAZIONE, 
	FINESTERILIZZAZIONE, INIZIOSTOCCAGGIO, FINESTOCCAGGIO, VISIBILELISTADETTAGLIO, SCELTARAPIDA, VISIBILEPRINCIPALE)
VALUES(1, --ID
'PULITO', -- DESCRIZIONE
'FINE STERILIZZAZIONE', --DESCRIZIONEAZIONE
'00000001', --BARCODE
100, --COLORE
0, --ELIMINATO
4, --VISIBILEMENU
4, --VISIBILELISTA
0, --INZIOCICLO
0, --INIZIOSTERILIZZAZIONE
1, --FINESTERILIZZAZIONE
0, --INIZIOSTOCCAGGIO
0, --FINESTOCCAGGIO
4, --VISIBILELISTADETTAGLIO, 
'F00', --SCELTARAPIDA 
0); --VISIBILEPRINCIPALE
COMMIT;

-- stato sporco
INSERT INTO STATO (ID, DESCRIZIONE, DESCRIZIONEAZIONE, BARCODE, COLORE, ELIMINATO, VISIBILEMENU, VISIBILELISTA, INIZIOCICLO, INIZIOSTERILIZZAZIONE, 
	FINESTERILIZZAZIONE, INIZIOSTOCCAGGIO, FINESTOCCAGGIO, VISIBILELISTADETTAGLIO, SCELTARAPIDA, VISIBILEPRINCIPALE)
VALUES(2, --ID
'SPORCO', -- DESCRIZIONE
'SPORCO', --DESCRIZIONEAZIONE
'00000002', --BARCODE
0, --COLORE
0, --ELIMINATO
1, --VISIBILEMENU
1, --VISIBILELISTA
1, --INZIOCICLO
0, --INIZIOSTERILIZZAZIONE
0, --FINESTERILIZZAZIONE
0, --INIZIOSTOCCAGGIO
0, --FINESTOCCAGGIO
1, --VISIBILELISTADETTAGLIO, 
'U00', --SCELTARAPIDA 
0); --VISIBILEPRINCIPALE
COMMIT;

-- stato sterilizzazione
INSERT INTO STATO (ID, DESCRIZIONE, DESCRIZIONEAZIONE, BARCODE, COLORE, ELIMINATO, VISIBILEMENU, VISIBILELISTA, INIZIOCICLO, INIZIOSTERILIZZAZIONE, 
	FINESTERILIZZAZIONE, INIZIOSTOCCAGGIO, FINESTOCCAGGIO, VISIBILELISTADETTAGLIO, SCELTARAPIDA, VISIBILEPRINCIPALE)
VALUES(3, --ID
'STERILIZZAZIONE', -- DESCRIZIONE
'INIZIO STERILIZZAZIONE', --DESCRIZIONEAZIONE
'00000003', --BARCODE
60, --COLORE
0, --ELIMINATO
3, --VISIBILEMENU
3, --VISIBILELISTA
0, --INZIOCICLO
1, --INIZIOSTERILIZZAZIONE
0, --FINESTERILIZZAZIONE
0, --INIZIOSTOCCAGGIO
0, --FINESTOCCAGGIO
3, --VISIBILELISTADETTAGLIO, 
'I00', --SCELTARAPIDA 
0); --VISIBILEPRINCIPALE
COMMIT;

-- stato lavaggio manuale
INSERT INTO STATO (ID, DESCRIZIONE, DESCRIZIONEAZIONE, BARCODE, COLORE, ELIMINATO, VISIBILEMENU, VISIBILELISTA, INIZIOCICLO, INIZIOSTERILIZZAZIONE, 
	FINESTERILIZZAZIONE, INIZIOSTOCCAGGIO, FINESTOCCAGGIO, VISIBILELISTADETTAGLIO, SCELTARAPIDA, VISIBILEPRINCIPALE)
VALUES(4, --ID
'LAVAGGIO MANUALE', -- DESCRIZIONE
'LAVAGGIO MANUALE', --DESCRIZIONEAZIONE
'00000004', --BARCODE
30, --COLORE
0, --ELIMINATO
2, --VISIBILEMENU
2, --VISIBILELISTA
0, --INZIOCICLO
0, --INIZIOSTERILIZZAZIONE
0, --FINESTERILIZZAZIONE
0, --INIZIOSTOCCAGGIO
0, --FINESTOCCAGGIO
2, --VISIBILELISTADETTAGLIO, 
'L00', --SCELTARAPIDA 
0); --VISIBILEPRINCIPALE
COMMIT;

-- stato inizio stoccaggio
INSERT INTO STATO (ID, DESCRIZIONE, DESCRIZIONEAZIONE, BARCODE, COLORE, ELIMINATO, VISIBILEMENU, VISIBILELISTA, INIZIOCICLO, INIZIOSTERILIZZAZIONE, 
	FINESTERILIZZAZIONE, INIZIOSTOCCAGGIO, FINESTOCCAGGIO, VISIBILELISTADETTAGLIO, SCELTARAPIDA, VISIBILEPRINCIPALE)
VALUES(5, --ID
'INIZIO STOCCAGGIO', -- DESCRIZIONE
'INIZIO STOCCAGGIO', --DESCRIZIONEAZIONE
'00000005', --BARCODE
180, --COLORE
0, --ELIMINATO
5, --VISIBILEMENU
5, --VISIBILELISTA
0, --INZIOCICLO
0, --INIZIOSTERILIZZAZIONE
0, --FINESTERILIZZAZIONE
1, --INIZIOSTOCCAGGIO
0, --FINESTOCCAGGIO
5, --VISIBILELISTADETTAGLIO, 
'S00', --SCELTARAPIDA 
0); --VISIBILEPRINCIPALE
COMMIT;

-- stato fine stoccaggio
INSERT INTO STATO (ID, DESCRIZIONE, DESCRIZIONEAZIONE, BARCODE, COLORE, ELIMINATO, VISIBILEMENU, VISIBILELISTA, INIZIOCICLO, INIZIOSTERILIZZAZIONE, 
	FINESTERILIZZAZIONE, INIZIOSTOCCAGGIO, FINESTOCCAGGIO, VISIBILELISTADETTAGLIO, SCELTARAPIDA, VISIBILEPRINCIPALE)
VALUES(6, --ID
'FINE STOCCAGGIO', -- DESCRIZIONE
'FINE STOCCAGGIO', --DESCRIZIONEAZIONE
'00000006', --BARCODE
100, --COLORE
0, --ELIMINATO
6, --VISIBILEMENU
6, --VISIBILELISTA
0, --INZIOCICLO
0, --INIZIOSTERILIZZAZIONE
0, --FINESTERILIZZAZIONE
0, --INIZIOSTOCCAGGIO
1, --FINESTOCCAGGIO
6, --VISIBILELISTADETTAGLIO, 
NULL, --SCELTARAPIDA 
0); --VISIBILEPRINCIPALE
COMMIT;

--TRANSAZIONI DI DEFAULT
INSERT INTO STATOCAMBIO(IDSTATOOLD, IDSTATONEW, IDSEDE) VALUES (2, 3, (SELECT MIN(ID) FROM SEDIESAME)); --SPORCO -> STERILIZZAZIONE
INSERT INTO STATOCAMBIO(IDSTATOOLD, IDSTATONEW, IDSEDE) VALUES (3, 1, (SELECT MIN(ID) FROM SEDIESAME)); --STERILIZZAZIONE -> PULITO
INSERT INTO STATOCAMBIO(IDSTATOOLD, IDSTATONEW, IDSEDE) VALUES (1, 5, (SELECT MIN(ID) FROM SEDIESAME)); --PULITO -> INIZIO STOCCAGGIO
INSERT INTO STATOCAMBIO(IDSTATOOLD, IDSTATONEW, IDSEDE) VALUES (5, 6, (SELECT MIN(ID) FROM SEDIESAME)); --INIZIO STOCCAGGIO -> FINE STOCCAGGIO
INSERT INTO STATOCAMBIO(IDSTATOOLD, IDSTATONEW, IDSEDE) VALUES (6, 2, (SELECT MIN(ID) FROM SEDIESAME)); --FINE STOCCAGGIO -> SPORCO
COMMIT;

-- AMLOGIN INSERIMENTO DATI UTENTI IN TABELLA UTENTI_PASSWORD
INSERT INTO UTENTI_PASSWORDS (IDUTENTE, DATAORA, PASSWORD, ELIMINATO)
SELECT ID, DATA_PASSWORD, PASSWORD, 0  
FROM UTENTI
WHERE ELIMINATO = 0;
COMMIT;


