ATTENZIONE VERIFICARE LA POSIZIONE DI SALVATAGGIO DEI FILE MDF ED LDF DI MSSQL
DATO CHE LA DIRECTORY DIPENDE DALLA VERSIONE DI SQL SERVER INSTALLATA.
CONTROLLARE 8 E 10 RIGHE PIU SOTTO ATTRIBUTO FILENAME

USE [master]
GO
/****** Object:  Database [CLEANTRACK]    Script Date: 02/04/2021 05:19:43 ******/
CREATE DATABASE [CLEANTRACK]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CLEANTRACK', FILENAME = N'D:\Program Files\Microsoft SQL Server\ \*--MSSQL14.MSSQLSERVER--*\ \MSSQL\DATA\CLEANTRACK.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CLEANTRACK_log', FILENAME = N'D:\Program Files\Microsoft SQL Server\ \*--MSSQL14.MSSQLSERVER--*\ \MSSQL\DATA\CLEANTRACK_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [CLEANTRACK] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CLEANTRACK].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [CLEANTRACK] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [CLEANTRACK] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [CLEANTRACK] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [CLEANTRACK] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [CLEANTRACK] SET ARITHABORT OFF 
GO
ALTER DATABASE [CLEANTRACK] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [CLEANTRACK] SET AUTO_SHRINK ON 
GO
ALTER DATABASE [CLEANTRACK] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [CLEANTRACK] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [CLEANTRACK] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [CLEANTRACK] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [CLEANTRACK] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [CLEANTRACK] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [CLEANTRACK] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [CLEANTRACK] SET  DISABLE_BROKER 
GO
ALTER DATABASE [CLEANTRACK] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [CLEANTRACK] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [CLEANTRACK] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [CLEANTRACK] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [CLEANTRACK] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [CLEANTRACK] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [CLEANTRACK] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [CLEANTRACK] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [CLEANTRACK] SET  MULTI_USER 
GO
ALTER DATABASE [CLEANTRACK] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [CLEANTRACK] SET DB_CHAINING OFF 
GO
ALTER DATABASE [CLEANTRACK] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [CLEANTRACK] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [CLEANTRACK] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [CLEANTRACK] SET QUERY_STORE = OFF
GO
USE [CLEANTRACK]
GO
/****** Object:  User [CLEANTRACK]    Script Date: 02/04/2021 05:19:44 ******/
CREATE USER [CLEANTRACK] WITHOUT LOGIN WITH DEFAULT_SCHEMA=[DBO]
GO
ALTER ROLE [db_owner] ADD MEMBER [CLEANTRACK]
GO
/****** Object:  Table [dbo].[TIPIDISPOSITIVI]    Script Date: 02/04/2021 05:19:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TIPIDISPOSITIVI](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIZIONE] [nvarchar](255) NULL,
 CONSTRAINT [PK_TIPIDISPOSITIVI] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[FORNITORI]    Script Date: 02/04/2021 05:19:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FORNITORI](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MATRICOLA] [nvarchar](50) NULL,
	[DESCRIZIONE] [nvarchar](255) NULL,
 CONSTRAINT [PK_FORNITORI] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DISPOSITIVI]    Script Date: 02/04/2021 05:19:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DISPOSITIVI](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MATRICOLA] [nvarchar](50) NULL,
	[SERIALE] [nvarchar](255) NULL,
	[DESCRIZIONE] [nvarchar](255) NULL,
	[IDTIPO] [int] NULL,
	[IDFORNITORE] [int] NULL,
	[STATO] [int] NULL,
	[ESAMIESEGUITI] [int] NULL,
	[DATAINIZIO] [nvarchar](14) NULL,
	[DATAFINE] [nvarchar](14) NULL,
	[DISMESSO] [bit] NULL,
	[IDCAUSALEDISMISSIONE] [int] NULL,
	[IDRFID1] [int] NULL,
	[IDRFID2] [int] NULL,
	[TAG] [varchar](50) NULL,
	[IDSEDE] [int] NOT NULL,
	[ELIMINATO] [bit] NOT NULL,
	[DATASTATO] [varchar](14) NULL,
	[IDOPERATORESTATO] [int] NULL,
 CONSTRAINT [PK_DISPOSITIVI] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[STATO]    Script Date: 02/04/2021 05:19:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[STATO](
	[ID] [int] NOT NULL,
	[DESCRIZIONE] [varchar](255) NOT NULL,
	[DESCRIZIONEAZIONE] [varchar](255) NULL,
	[BARCODE] [varchar](255) NULL,
	[COLORE] [int] NOT NULL,
	[ELIMINATO] [bit] NOT NULL,
	[VISIBILEMENU] [int] NOT NULL,
	[VISIBILELISTA] [int] NOT NULL,
	[INIZIOCICLO] [bit] NOT NULL,
	[INIZIOSTERILIZZAZIONE] [bit] NOT NULL,
	[FINESTERILIZZAZIONE] [bit] NOT NULL,
	[INIZIOSTOCCAGGIO] [bit] NOT NULL,
	[FINESTOCCAGGIO] [bit] NOT NULL,
	[VISIBILELISTADETTAGLIO] [int] NOT NULL,
	[SCELTARAPIDA] [varchar](50) NULL,
	[VISIBILEPRINCIPALE] [int] NOT NULL,
	[INIZIOPRELAVAGGIO] [bit] NOT NULL,
	[FINEPRELAVAGGIO] [bit] NOT NULL,
 CONSTRAINT [PK_STATO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CICLI]    Script Date: 02/04/2021 05:19:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CICLI](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[IDDISPOSITIVO] [int] NULL,
	[DATAESAME] [varchar](14) NULL,
	[IDOPERATOREESAME] [int] NULL,
	[IDESAME] [int] NULL,
	[IDSEDEESAME] [int] NULL,
	[IDUOESAME] [int] NULL,
	[TIPOESAME] [varchar](255) NULL,
	[IDPAZIENTE] [varchar](50) NULL,
	[SALA] [varchar](255) NULL,
	[DATACONSEGNA] [varchar](14) NULL,
	[IDOPERATORECONSEGNA] [int] NULL,
	[DATATESTTENUTA] [varchar](14) NULL,
	[IDOPERATORETESTTENUTA] [int] NULL,
	[DATAINIZIOSTERILIZZAZIONE] [varchar](14) NULL,
	[IDOPERATOREINIZIOSTERILIZZAZIO] [int] NULL,
	[DATAFINESTERILIZZAZIONE] [varchar](14) NULL,
	[IDOPERATOREFINESTERILIZZAZIONE] [int] NULL,
	[IDSTERILIZZATRICE] [int] NULL,
	[DATAARMADIO] [varchar](14) NULL,
	[IDOPERATOREARMADIO] [int] NULL,
	[DATAPRELAVAGGIO] [varchar](14) NULL,
	[IDOPERATOREPRELAVAGGIO] [int] NULL,
	[IDVASCA] [varchar](14) NULL,
	[MACHINECYCLEID] [varchar](50) NULL,
	[DISINFECTANTCYCLEID] [varchar](50) NULL,
	[FAILED] [bit] NOT NULL,
	[MODIFICAMANUALE] [bit] NOT NULL,
 CONSTRAINT [PK_CICLI] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  View [dbo].[VISTADISPOSITIVI]    Script Date: 02/04/2021 05:19:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VISTADISPOSITIVI]
AS
SELECT        DBO.DISPOSITIVI.ID, DBO.DISPOSITIVI.MATRICOLA, DBO.DISPOSITIVI.DESCRIZIONE, DBO.DISPOSITIVI.ESAMIESEGUITI,
                             (SELECT        COUNT(*) AS EXPR1
                               FROM            DBO.CICLI
                               WHERE        (IDDISPOSITIVO = DBO.DISPOSITIVI.ID)) AS CICLIESEGUITI, DBO.DISPOSITIVI.IDFORNITORE, DBO.FORNITORI.DESCRIZIONE AS FORNITORE, DBO.DISPOSITIVI.IDTIPO, DBO.TIPIDISPOSITIVI.DESCRIZIONE AS TIPODISPOSITIVO, 
                         DBO.STATO.ID AS IDSTATO, DBO.STATO.DESCRIZIONE AS STATO, DBO.DISPOSITIVI.DISMESSO, DBO.DISPOSITIVI.IDSEDE
FROM            DBO.DISPOSITIVI INNER JOIN
                         DBO.STATO ON DBO.DISPOSITIVI.STATO = DBO.STATO.ID LEFT OUTER JOIN
                         DBO.FORNITORI ON DBO.DISPOSITIVI.IDFORNITORE = DBO.FORNITORI.ID LEFT OUTER JOIN
                         DBO.TIPIDISPOSITIVI ON DBO.DISPOSITIVI.IDTIPO = DBO.TIPIDISPOSITIVI.ID
WHERE        (DBO.DISPOSITIVI.ELIMINATO = 0)
GO
/****** Object:  Table [dbo].[CICLISTATOLOG]    Script Date: 02/04/2021 05:19:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CICLISTATOLOG](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[IDCICLO] [int] NOT NULL,
	[IDSTATOOLD] [int] NOT NULL,
	[IDSTATONEW] [int] NOT NULL,
	[IDOPERATORE] [int] NOT NULL,
	[DATAORA] [varchar](14) NOT NULL,
 CONSTRAINT [PK_CICLISTATOLOG] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  View [dbo].[VISTADISPOSITIVIULTIMOCICLO]    Script Date: 02/04/2021 05:19:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VISTADISPOSITIVIULTIMOCICLO]
AS
SELECT        DBO.VISTADISPOSITIVI.ID, DBO.VISTADISPOSITIVI.MATRICOLA, DBO.VISTADISPOSITIVI.DESCRIZIONE, DBO.VISTADISPOSITIVI.IDSTATO, DBO.VISTADISPOSITIVI.STATO, DBO.VISTADISPOSITIVI.IDFORNITORE, DBO.VISTADISPOSITIVI.IDTIPO, 
                         DBO.VISTADISPOSITIVI.DISMESSO,
                             (SELECT        COUNT(*) AS EXPR1
                               FROM            DBO.CICLI
                               WHERE        (IDDISPOSITIVO = DBO.VISTADISPOSITIVI.ID)) AS CICLIESEGUITI, A.IDSTATOOLD, A.IDSTATONEW, A.IDOPERATORE, A.DATAORA, DBO.VISTADISPOSITIVI.IDSEDE
FROM            DBO.VISTADISPOSITIVI LEFT OUTER JOIN
                             (SELECT        DBO.CICLISTATOLOG.IDCICLO, DBO.CICLISTATOLOG.IDSTATOOLD, DBO.CICLISTATOLOG.IDSTATONEW, DBO.CICLISTATOLOG.IDOPERATORE, DBO.CICLISTATOLOG.DATAORA
                               FROM            DBO.CICLISTATOLOG INNER JOIN
                                                         DBO.STATO ON DBO.CICLISTATOLOG.IDSTATONEW = DBO.STATO.ID
                               WHERE        (DBO.STATO.VISIBILELISTA > 0)) AS A ON A.IDCICLO =
                             (SELECT        MAX(ID) AS EXPR1
                               FROM            DBO.CICLI
                               WHERE        (IDDISPOSITIVO = DBO.VISTADISPOSITIVI.ID))
GO
/****** Object:  Table [dbo].[OPERATORI]    Script Date: 02/04/2021 05:19:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[OPERATORI](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MATRICOLA] [nvarchar](50) NULL,
	[COGNOME] [nvarchar](50) NULL,
	[NOME] [nvarchar](50) NULL,
	[DISATTIVATO] [int] NULL,
	[ID_UTENTE] [bigint] NULL,
	[IDRFID1] [int] NULL,
	[IDRFID2] [int] NULL,
	[TAG] [varchar](50) NULL,
 CONSTRAINT [PK_OPERATORI] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  View [dbo].[VISTADISPOSITIVICICLI]    Script Date: 02/04/2021 05:19:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VISTADISPOSITIVICICLI]
AS
SELECT VISTADISPOSITIVI.ID, CICLI.ID AS IDCICLO, CICLI.IDPAZIENTE, CICLI.IDESAME, CICLI.SALA,
       CICLISTATOLOG.IDSTATOOLD, CICLISTATOLOG.IDSTATONEW, 
       CICLISTATOLOG.DATAORA, CICLISTATOLOG.IDOPERATORE, OPERATORI.COGNOME, OPERATORI.NOME
FROM VISTADISPOSITIVI
     INNER JOIN CICLI ON VISTADISPOSITIVI.ID = CICLI.IDDISPOSITIVO
     LEFT OUTER JOIN CICLISTATOLOG ON CICLISTATOLOG.IDCICLO = CICLI.ID
     LEFT OUTER JOIN OPERATORI ON OPERATORI.ID = CICLISTATOLOG.IDOPERATORE
GO
/****** Object:  View [dbo].[ENDOSCOPI_OLYMPUS]    Script Date: 02/04/2021 05:19:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[ENDOSCOPI_OLYMPUS] AS
SELECT DESCRIZIONE AS MODELLO_ENDOSCOPIO, SERIALE AS N_SERIE_ENDOSCOPIO, TAG AS N_TRANSPONDER_ENDOSCOPIO
FROM DISPOSITIVI
WHERE ELIMINATO = 0
GO
/****** Object:  View [dbo].[PROCEDURE_OLYMPUS]    Script Date: 02/04/2021 05:19:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[PROCEDURE_OLYMPUS] AS (SELECT PART1.N_PROTOCOLLO,
	   PART1.N_TANSPONDER_ENDOSCOPICO,
	   PART1.MODELLO_ENDOSCOPIO,
	   PART1.N_SERIE_ENDOSCOPIO,
	   OPERATORI.MATRICOLA,
	   OPERATORI.COGNOME,
	   OPERATORI.NOME,
	   PART1.DESCRIZIONE_PROCEDURA,
	   PART1.ESITO_PROCEDURA,
	   PART1.DATAORAINIZIO,
	   PART1.DATAORAFINE
FROM
(
SELECT CICLI.ID AS N_PROTOCOLLO,
	   DISPOSITIVI.TAG AS N_TANSPONDER_ENDOSCOPICO,
	   DISPOSITIVI.DESCRIZIONE AS MODELLO_ENDOSCOPIO,
	   DISPOSITIVI.SERIALE AS N_SERIE_ENDOSCOPIO,
	   (SELECT IDOPERATORE
	   FROM (
			SELECT IDCICLO, DATAORA, IDOPERATORE, ROW_NUMBER() OVER(PARTITION BY IDCICLO ORDER BY DATAORA DESC) AS NUM
			FROM CICLISTATOLOG
			--WHERE IDSTATONEW IN (10,5)-- AND IDCICLO = 277
	   )OPERCODE
	   WHERE OPERCODE.NUM = 1 AND CICLI.ID = OPERCODE.IDCICLO) AS IDOPERATORE,
	   (CASE (SELECT IDSTATONEW
			  FROM (
					SELECT IDCICLO, IDSTATONEW, ROW_NUMBER() OVER(PARTITION BY IDCICLO ORDER BY DATAORA DESC) AS NUM
					FROM CICLISTATOLOG
					--WHERE IDCICLO = 277
			  )OPERCODE
			  WHERE OPERCODE.NUM = 1 AND CICLI.ID = OPERCODE.IDCICLO)
		WHEN 5 THEN 'LAVAGGIO + STOCCAGGIO' WHEN 1 THEN 'LAVAGGIO' WHEN 7 THEN 'LAVAGGIO' ELSE '' END) AS DESCRIZIONE_PROCEDURA,
	   (CASE CICLI.FAILED WHEN 1 THEN 0 ELSE (
			CASE (
					SELECT IDSTATONEW
					FROM (
						SELECT IDCICLO, IDSTATONEW, ROW_NUMBER() OVER(PARTITION BY IDCICLO ORDER BY DATAORA DESC) AS NUM
						FROM CICLISTATOLOG
					)TEMP1 WHERE TEMP1.NUM = 1 AND CICLI.ID = TEMP1.IDCICLO
				 ) 
			WHEN 1 THEN 1 WHEN 5 THEN 1 WHEN 7 THEN 1 ELSE 0 END) END) AS ESITO_PROCEDURA,
	   (SELECT DATAORA
	   FROM(
			SELECT IDCICLO, DATAORA, ROW_NUMBER() OVER(PARTITION BY IDCICLO ORDER BY DATAORA DESC) AS NUM
			FROM CICLISTATOLOG
			WHERE IDSTATONEW = 2 --AND IDCICLO = 277
	   )DATAIN
	   WHERE DATAIN.NUM = 1 AND CICLI.ID = DATAIN.IDCICLO) AS DATAORAINIZIO,
	   (SELECT (CASE WHEN IDSTATONEW = 1 OR IDSTATONEW = 5 OR IDSTATONEW = 7 THEN DATAORA ELSE NULL END) AS DATAORA
	   FROM(
			SELECT IDCICLO, DATAORA, IDSTATONEW, ROW_NUMBER() OVER(PARTITION BY IDCICLO ORDER BY DATAORA DESC) AS NUM
			FROM CICLISTATOLOG
			--WHERE IDSTATONEW IN (10,5) --AND IDCICLO = 277
	   )DATAOUT
	   WHERE DATAOUT.NUM = 1 AND CICLI.ID = DATAOUT.IDCICLO) AS DATAORAFINE
FROM CICLI LEFT JOIN DISPOSITIVI ON CICLI.IDDISPOSITIVO = DISPOSITIVI.ID
WHERE CICLI.ID IN (
SELECT CICLI_ID
FROM(
SELECT MAX(CICLI.ID) AS CICLI_ID,
	   DISPOSITIVI.TAG AS DISPOSITIVI_TAG,
	   DISPOSITIVI.DESCRIZIONE AS DISPOSITIVI_DESC,
	   DISPOSITIVI.SERIALE AS DISPOSITIVI_SERIAL
FROM CICLI JOIN DISPOSITIVI ON CICLI.IDDISPOSITIVO = DISPOSITIVI.ID
WHERE DISPOSITIVI.DISMESSO = 0 AND DISPOSITIVI.ELIMINATO = 0
GROUP BY DISPOSITIVI.TAG, DISPOSITIVI.DESCRIZIONE, DISPOSITIVI.SERIALE
)TABCICLI)
)PART1 LEFT JOIN OPERATORI ON PART1.IDOPERATORE = OPERATORI.ID)
GO
/****** Object:  View [dbo].[UTENTI_OLYMPUS]    Script Date: 02/04/2021 05:19:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[UTENTI_OLYMPUS] AS
SELECT MATRICOLA AS N_UTENTE, COGNOME AS COGNOME_UTENTE, NOME AS NOME_UTENTE
FROM OPERATORI
WHERE DISATTIVATO = 0
GO
/****** Object:  View [dbo].[CLEANTRACK_DISPOSITIVI]    Script Date: 02/04/2021 05:19:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[CLEANTRACK_DISPOSITIVI] AS
SELECT     ID, MATRICOLA, IDRFID1, IDRFID2, DESCRIZIONE, STATO, ESAMIESEGUITI, DISMESSO, DATAINIZIO
FROM         DISPOSITIVI
GO
/****** Object:  Table [dbo].[MAIL]    Script Date: 02/04/2021 05:19:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MAIL](
	[NOME] [varchar](50) NULL,
	[COGNOME] [varchar](50) NULL,
	[MAIL] [varchar](50) NOT NULL,
	[ELIMINATO] [int] NOT NULL,
	[ID] [int] IDENTITY(1,1) NOT NULL
) ON [PRIMARY]
GO
/****** Object:  View [dbo].[CLEANTRACK_MAIL]    Script Date: 02/04/2021 05:19:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[CLEANTRACK_MAIL] AS
SELECT     MAIL, ELIMINATO, ID
FROM         MAIL
GO
/****** Object:  View [dbo].[CLEANTRACK_OPERATORI]    Script Date: 02/04/2021 05:19:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[CLEANTRACK_OPERATORI] AS
SELECT     ID, MATRICOLA, IDRFID1, IDRFID2, COGNOME, NOME, DISATTIVATO
FROM         OPERATORI
GO
/****** Object:  Table [dbo].[TIPIDISPOSITIVISTATOSCADENZA]    Script Date: 02/04/2021 05:19:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TIPIDISPOSITIVISTATOSCADENZA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[IDTIPODISPOSITIVO] [int] NOT NULL,
	[IDSTATO] [int] NOT NULL,
	[SCADENZAMINUTI] [int] NOT NULL,
	[IDSTATODESTINAZIONE] [int] NOT NULL,
	[ELIMINATO] [bit] NOT NULL,
 CONSTRAINT [PK_TDISPSTATOSCADENZA] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  View [dbo].[VISTADISPOSITIVISCADUTI]    Script Date: 02/04/2021 05:19:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW  [dbo].[VISTADISPOSITIVISCADUTI] AS 
SELECT DBO.DISPOSITIVI.ID, DBO.DISPOSITIVI.STATO, DBO.TIPIDISPOSITIVISTATOSCADENZA.IDSTATODESTINAZIONE, DBO.DISPOSITIVI.IDOPERATORESTATO, DBO.DISPOSITIVI.DISMESSO, DBO.DISPOSITIVI.ELIMINATO
FROM DBO.DISPOSITIVI INNER JOIN
     DBO.TIPIDISPOSITIVISTATOSCADENZA ON DBO.DISPOSITIVI.IDTIPO = DBO.TIPIDISPOSITIVISTATOSCADENZA.IDTIPODISPOSITIVO AND DBO.DISPOSITIVI.STATO = DBO.TIPIDISPOSITIVISTATOSCADENZA.IDSTATO AND 
     DATEDIFF(MINUTE, CONVERT(DATETIME, STUFF(STUFF(STUFF(DBO.DISPOSITIVI.DATASTATO, 9, 0, ' '), 12, 0, ':'), 15, 0, ':')), GETDATE()) > DBO.TIPIDISPOSITIVISTATOSCADENZA.SCADENZAMINUTI
WHERE (DBO.DISPOSITIVI.DISMESSO = 0) AND (DBO.DISPOSITIVI.ELIMINATO = 0)
GO
/****** Object:  View [dbo].[AM_GETSERVERDATE]    Script Date: 02/04/2021 05:19:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[AM_GETSERVERDATE] AS 
SELECT     SUBSTRING(DATAORA, 1, 4) + SUBSTRING(DATAORA, 6, 2) + SUBSTRING(DATAORA, 9, 2) + SUBSTRING(DATAORA, 12, 2) + SUBSTRING(DATAORA, 15, 2) 
                      + SUBSTRING(DATAORA, 18, 2) AS DATA
FROM         (SELECT     CONVERT(VARCHAR(50), GETDATE(), 120) AS DATAORA) AS A
GO
/****** Object:  Table [dbo].[ARMADI_LAVATRICI]    Script Date: 02/04/2021 05:19:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ARMADI_LAVATRICI](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MATRICOLA] [varchar](50) NULL,
	[DESCRIZIONE] [varchar](255) NULL,
	[SERIALE] [varchar](50) NULL,
	[DISMESSO] [bit] NULL,
	[IDCAUSALEDISMISSIONE] [int] NULL,
	[DATAFINE] [varchar](50) NULL,
	[TEMPOLAVAGGIO] [int] NULL,
	[IDSEDE] [int] NOT NULL,
	[TIPO] [int] NOT NULL,
	[PERCORSO] [varchar](255) NULL,
	[POLLINGTIME] [int] NOT NULL,
 CONSTRAINT [PK_STERILIZZATRICI] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CAUSALI]    Script Date: 02/04/2021 05:19:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CAUSALI](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CAUSALE] [nvarchar](255) NULL,
 CONSTRAINT [PK_CAUSALI] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CICLIEXT]    Script Date: 02/04/2021 05:19:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CICLIEXT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[IDCICLO] [int] NOT NULL,
	[DESCRIZIONE] [varchar](50) NULL,
	[VALORE] [varchar](255) NULL,
	[DATA] [varchar](14) NULL,
	[ERROR] [bit] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CONFIGURAZIONE]    Script Date: 02/04/2021 05:19:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONFIGURAZIONE](
	[CHIAVE] [varchar](50) NOT NULL,
	[VALORE] [varchar](4000) NULL,
 CONSTRAINT [PK_CONFIGURAZIONE] PRIMARY KEY CLUSTERED 
(
	[CHIAVE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CONFIGURAZIONIAMLOGIN]    Script Date: 02/04/2021 05:19:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONFIGURAZIONIAMLOGIN](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[VOCE] [varchar](255) NULL,
	[VALORE] [varchar](255) NULL,
	[IDUO] [int] NOT NULL,
	[ELIMINATO] [bit] NOT NULL,
 CONSTRAINT [PK_CONFIGURAZIONIAMLOGIN] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[GRUPPI]    Script Date: 02/04/2021 05:19:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GRUPPI](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOME] [varchar](50) NULL,
	[DESCRIZIONE] [varchar](50) NULL,
	[PERMESSI] [int] NULL,
	[PERMESSI2] [int] NULL,
	[ELIMINATO] [bit] NOT NULL,
 CONSTRAINT [PK_GRUPPI] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LETTORI]    Script Date: 02/04/2021 05:19:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LETTORI](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIZIONE] [varchar](255) NOT NULL,
	[IP] [varchar](50) NOT NULL,
	[PORTA] [int] NOT NULL,
	[IDSTATODEFAULT] [int] NULL,
	[TIPO] [int] NOT NULL,
	[ELIMINATO] [bit] NOT NULL,
	[ETICHETTAOPERAZIONE] [varchar](50) NULL,
	[ETICHETTADISPOSITIVO] [varchar](50) NULL,
	[ETICHETTAOPERATORE] [varchar](50) NULL,
	[TIMEOUTCOMPLETAMENTOSTEP] [int] NULL,
	[SELEZIONEWORKLIST] [bit] NOT NULL,
	[ATTESAPRIMAAPPLICA] [int] NULL,
	[ATTESAPRIMACHIUSURAPOPUP] [int] NOT NULL,
	[IDSEDE] [int] NOT NULL,
 CONSTRAINT [PK_LETTORI_BADGE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LOG]    Script Date: 02/04/2021 05:19:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LOG](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[UTENTE] [varchar](50) NULL,
	[TABELLA] [varchar](50) NULL,
	[OPERAZIONE] [varchar](50) NULL,
	[DATA] [varchar](14) NULL,
	[RECORD] [int] NULL,
	[CLASSEELEMENTO] [varchar](100) NULL,
	[NOMECAMPO] [varchar](100) NULL,
	[VALOREORIGINALE] [nvarchar](255) NULL,
	[VALOREMODIFICATO] [nvarchar](255) NULL,
 CONSTRAINT [PK_LOG] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LOGEXT]    Script Date: 02/04/2021 05:19:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LOGEXT](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[DATEEVENT] [varchar](14) NOT NULL,
	[CURRENTHOST] [varchar](255) NOT NULL,
	[MODULENAME] [varchar](255) NOT NULL,
	[CALLERHOST] [varchar](255) NULL,
	[ORIGIN] [varchar](255) NOT NULL,
	[LOGLEVEL] [varchar](255) NOT NULL,
	[DESCRIPTION] [varchar](1024) NULL,
	[ATTACHMENT] [text] NULL,
 CONSTRAINT [PK_LOGEXT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[OPERATORI_SEDI]    Script Date: 02/04/2021 05:19:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[OPERATORI_SEDI](
	[IDOPERATORE] [int] NOT NULL,
	[IDSEDE] [int] NOT NULL,
 CONSTRAINT [PK_OPERATORI_SEDI] PRIMARY KEY CLUSTERED 
(
	[IDOPERATORE] ASC,
	[IDSEDE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SEDIESAME]    Script Date: 02/04/2021 05:19:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SEDIESAME](
	[ID] [int] NOT NULL,
	[DESCRIZIONE] [varchar](255) NULL,
	[ELIMINATO] [bit] NOT NULL,
 CONSTRAINT [PK_SEDIESAME] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[STATOCAMBIO]    Script Date: 02/04/2021 05:19:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[STATOCAMBIO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[IDSTATOOLD] [int] NOT NULL,
	[IDSTATONEW] [int] NOT NULL,
	[ELIMINATO] [bit] NOT NULL,
	[IDSEDE] [int] NOT NULL,
 CONSTRAINT [PK_STATOCAMBIO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[STERILIZZATRICIPARSING]    Script Date: 02/04/2021 05:19:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[STERILIZZATRICIPARSING](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[IDSTERILIZZATRICE] [int] NOT NULL,
	[DATAPARSING] [varchar](14) NOT NULL,
	[FILENAMEDATA] [varchar](14) NOT NULL,
	[FILENAME] [varchar](255) NULL,
	[CONTENUTOFILE] [text] NULL,
	[CICLOCOMPLETO] [bit] NOT NULL,
	[ERROREIMPORT] [int] NOT NULL,
	[IDDISPOSITIVO] [int] NULL,
	[DATAORASTART] [varchar](14) NULL,
	[IDOPERATORESTART] [int] NULL,
	[DATAORAEND] [varchar](14) NULL,
	[IDOPERATOREEND] [int] NULL,
	[DATASTATODISPOSITIVO] [varchar](14) NULL,
	[STATODISPOSITIVO] [int] NULL,
 CONSTRAINT [PK_STERILIZZATRICIPARSING] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[STORICODISMISSIONE]    Script Date: 02/04/2021 05:19:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[STORICODISMISSIONE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DISMISSIONE] [int] NOT NULL,
	[DATA] [varchar](14) NULL,
	[CAUSALE] [varchar](255) NULL,
	[UTENTE] [varchar](50) NOT NULL,
	[IDDISPOSITIVO] [int] NOT NULL,
	[ELIMINATO] [int] NOT NULL,
 CONSTRAINT [PK_DISMISSIONHISTORY] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UO]    Script Date: 02/04/2021 05:19:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UO](
	[ID] [int] NOT NULL,
	[DESCRIZIONE] [nvarchar](50) NOT NULL,
	[ELIMINATO] [bit] NOT NULL,
 CONSTRAINT [PK_UO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UO_SEDI]    Script Date: 02/04/2021 05:19:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UO_SEDI](
	[IDUO] [int] NOT NULL,
	[IDSEDE] [int] NOT NULL,
 CONSTRAINT [PK_UO_SEDI] PRIMARY KEY CLUSTERED 
(
	[IDUO] ASC,
	[IDSEDE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UTENTI]    Script Date: 02/04/2021 05:19:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UTENTI](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[USERNAME] [varchar](50) NULL,
	[PASSWORD] [varchar](50) NULL,
	[ID_GRUPPO] [int] NOT NULL,
	[DISABILITATO] [bit] NOT NULL,
	[SCADENZA_PASSWORD] [int] NOT NULL,
	[DATA_PASSWORD] [varchar](14) NOT NULL,
	[DATA_ULTIMO_UTILIZZO] [varchar](14) NOT NULL,
	[PRIMO_LOGIN] [bit] NOT NULL,
	[DESCRIZIONE] [varchar](255) NULL,
	[TIPO_PASSWORD] [int] NOT NULL,
	[ELIMINATO] [bit] NOT NULL,
	[CODICEINTEGRAZIONE] [varchar](255) NULL,
 CONSTRAINT [PK_UTENTI] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UTENTI_LOG]    Script Date: 02/04/2021 05:19:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UTENTI_LOG](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USERNAME] [varchar](50) NOT NULL,
	[EVENTO] [int] NOT NULL,
	[DATA] [varchar](14) NOT NULL,
 CONSTRAINT [PK_UTENTI_LOG] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UTENTI_PASSWORDS]    Script Date: 02/04/2021 05:19:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UTENTI_PASSWORDS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[IDUTENTE] [int] NULL,
	[DATAORA] [varchar](14) NULL,
	[PASSWORD] [varchar](4000) NULL,
	[ELIMINATO] [bit] NOT NULL,
 CONSTRAINT [PK_UTENTI_PASSWORDS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UTENTI_SETTING]    Script Date: 02/04/2021 05:19:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UTENTI_SETTING](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[IDUTENTE] [bigint] NOT NULL,
	[CHIAVE] [varchar](50) NOT NULL,
	[VALORE] [varchar](255) NULL,
 CONSTRAINT [PK_UTENTI_SETTINGS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ARMADI_LAVATRICI] ADD  CONSTRAINT [DF_STERILIZZATRICI_DISMESSO]  DEFAULT ((0)) FOR [DISMESSO]
GO
ALTER TABLE [dbo].[ARMADI_LAVATRICI] ADD  CONSTRAINT [DF__STERILIZZA__TIPO__038683F8]  DEFAULT ((0)) FOR [TIPO]
GO
ALTER TABLE [dbo].[ARMADI_LAVATRICI] ADD  CONSTRAINT [DF__STERILIZZ__POLLI__047AA831]  DEFAULT ((0)) FOR [POLLINGTIME]
GO
ALTER TABLE [dbo].[CICLI] ADD  CONSTRAINT [DF__CICLI__FAILED__2D27B809]  DEFAULT ((0)) FOR [FAILED]
GO
ALTER TABLE [dbo].[CICLI] ADD  CONSTRAINT [DF__CICLI__MODIFICAM__76969D2E]  DEFAULT ((0)) FOR [MODIFICAMANUALE]
GO
ALTER TABLE [dbo].[CICLIEXT] ADD  CONSTRAINT [DF__CICLIEXT__ERROR__32E0915F]  DEFAULT ((0)) FOR [ERROR]
GO
ALTER TABLE [dbo].[CONFIGURAZIONIAMLOGIN] ADD  DEFAULT ((0)) FOR [IDUO]
GO
ALTER TABLE [dbo].[CONFIGURAZIONIAMLOGIN] ADD  DEFAULT ((0)) FOR [ELIMINATO]
GO
ALTER TABLE [dbo].[DISPOSITIVI] ADD  CONSTRAINT [DF_DISPOSITIVI_ESAMIESEGUITI]  DEFAULT ((0)) FOR [ESAMIESEGUITI]
GO
ALTER TABLE [dbo].[DISPOSITIVI] ADD  CONSTRAINT [DF_DISPOSITIVI_DISMESSO]  DEFAULT ((0)) FOR [DISMESSO]
GO
ALTER TABLE [dbo].[DISPOSITIVI] ADD  CONSTRAINT [DF_DISPOSITIVI_ELIMINATO]  DEFAULT ((0)) FOR [ELIMINATO]
GO
ALTER TABLE [dbo].[GRUPPI] ADD  CONSTRAINT [DF_PERMESSI]  DEFAULT ((0)) FOR [PERMESSI]
GO
ALTER TABLE [dbo].[GRUPPI] ADD  CONSTRAINT [DF_GRUPPI_PERMESSI2]  DEFAULT ((0)) FOR [PERMESSI2]
GO
ALTER TABLE [dbo].[GRUPPI] ADD  CONSTRAINT [DF_GRUPPI_ELIMINATO]  DEFAULT ((0)) FOR [ELIMINATO]
GO
ALTER TABLE [dbo].[LETTORI] ADD  DEFAULT ((0)) FOR [TIPO]
GO
ALTER TABLE [dbo].[LETTORI] ADD  DEFAULT ((0)) FOR [ELIMINATO]
GO
ALTER TABLE [dbo].[LETTORI] ADD  DEFAULT ((0)) FOR [SELEZIONEWORKLIST]
GO
ALTER TABLE [dbo].[LETTORI] ADD  DEFAULT ((0)) FOR [ATTESAPRIMACHIUSURAPOPUP]
GO
ALTER TABLE [dbo].[MAIL] ADD  DEFAULT ((0)) FOR [ELIMINATO]
GO
ALTER TABLE [dbo].[OPERATORI] ADD  CONSTRAINT [DF_OPERATORI_DISATTIVATO]  DEFAULT ((0)) FOR [DISATTIVATO]
GO
ALTER TABLE [dbo].[SEDIESAME] ADD  CONSTRAINT [DF_SEDIESAME_ELIMINATO]  DEFAULT ((0)) FOR [ELIMINATO]
GO
ALTER TABLE [dbo].[STATO] ADD  CONSTRAINT [DF__STATO__COLORE__7E02B4CC]  DEFAULT ((0)) FOR [COLORE]
GO
ALTER TABLE [dbo].[STATO] ADD  CONSTRAINT [DF_STATO_ELIMINATO]  DEFAULT ((0)) FOR [ELIMINATO]
GO
ALTER TABLE [dbo].[STATO] ADD  CONSTRAINT [DF__STATO__VISIBILEM__5006DFF2]  DEFAULT ((0)) FOR [VISIBILEMENU]
GO
ALTER TABLE [dbo].[STATO] ADD  CONSTRAINT [DF__STATO__VISIBILEL__50FB042B]  DEFAULT ((0)) FOR [VISIBILELISTA]
GO
ALTER TABLE [dbo].[STATO] ADD  CONSTRAINT [DF__STATO__INIZIOCIC__6225902D]  DEFAULT ((0)) FOR [INIZIOCICLO]
GO
ALTER TABLE [dbo].[STATO] ADD  CONSTRAINT [DF__STATO__INIZIOSTE__1975C517]  DEFAULT ((0)) FOR [INIZIOSTERILIZZAZIONE]
GO
ALTER TABLE [dbo].[STATO] ADD  CONSTRAINT [DF__STATO__FINESTERI__02925FBF]  DEFAULT ((0)) FOR [FINESTERILIZZAZIONE]
GO
ALTER TABLE [dbo].[STATO] ADD  CONSTRAINT [DF_STATO_INIZIOSTOCCAGGIO]  DEFAULT ((0)) FOR [INIZIOSTOCCAGGIO]
GO
ALTER TABLE [dbo].[STATO] ADD  CONSTRAINT [DF_STATO_FINESTOCCAGGIO]  DEFAULT ((0)) FOR [FINESTOCCAGGIO]
GO
ALTER TABLE [dbo].[STATO] ADD  CONSTRAINT [DF__STATO__VISIBILEL__2C88998B]  DEFAULT ((0)) FOR [VISIBILELISTADETTAGLIO]
GO
ALTER TABLE [dbo].[STATO] ADD  CONSTRAINT [DF__STATO__VISIBILEP__1387E197]  DEFAULT ((0)) FOR [VISIBILEPRINCIPALE]
GO
ALTER TABLE [dbo].[STATO] ADD  CONSTRAINT [DF_STATO_INIZIOPRELAVAGGIO]  DEFAULT ((0)) FOR [INIZIOPRELAVAGGIO]
GO
ALTER TABLE [dbo].[STATO] ADD  CONSTRAINT [DF_STATO_FINEPRELAVAGGIO]  DEFAULT ((0)) FOR [FINEPRELAVAGGIO]
GO
ALTER TABLE [dbo].[STATOCAMBIO] ADD  DEFAULT ((0)) FOR [ELIMINATO]
GO
ALTER TABLE [dbo].[STERILIZZATRICIPARSING] ADD  DEFAULT ((0)) FOR [CICLOCOMPLETO]
GO
ALTER TABLE [dbo].[STERILIZZATRICIPARSING] ADD  DEFAULT ((0)) FOR [ERROREIMPORT]
GO
ALTER TABLE [dbo].[TIPIDISPOSITIVISTATOSCADENZA] ADD  CONSTRAINT [DF__TIPIDISPO__ELIMI__6BAEFA67]  DEFAULT ((0)) FOR [ELIMINATO]
GO
ALTER TABLE [dbo].[UO] ADD  CONSTRAINT [DF_UO_ELIMINATO]  DEFAULT ((0)) FOR [ELIMINATO]
GO
ALTER TABLE [dbo].[UTENTI] ADD  CONSTRAINT [DF_UTENTI_ID_GRUPPO]  DEFAULT ((0)) FOR [ID_GRUPPO]
GO
ALTER TABLE [dbo].[UTENTI] ADD  CONSTRAINT [DF_UTENTI_DISABILITATO]  DEFAULT ((0)) FOR [DISABILITATO]
GO
ALTER TABLE [dbo].[UTENTI] ADD  CONSTRAINT [DF_UTENTI_SCADENZA_PASSWORD]  DEFAULT ((365)) FOR [SCADENZA_PASSWORD]
GO
ALTER TABLE [dbo].[UTENTI] ADD  CONSTRAINT [DF_UTENTI_DATA_PASSWORD]  DEFAULT ((20081209000000.)) FOR [DATA_PASSWORD]
GO
ALTER TABLE [dbo].[UTENTI] ADD  CONSTRAINT [DF_UTENTI_DATA_ULTIMO_UTILIZZO]  DEFAULT ((20081209000000.)) FOR [DATA_ULTIMO_UTILIZZO]
GO
ALTER TABLE [dbo].[UTENTI] ADD  CONSTRAINT [DF_UTENTI_PRIMO_LOGIN]  DEFAULT ((0)) FOR [PRIMO_LOGIN]
GO
ALTER TABLE [dbo].[UTENTI] ADD  CONSTRAINT [DF_UTENTI_TIPO_PASSWORD]  DEFAULT ((0)) FOR [TIPO_PASSWORD]
GO
ALTER TABLE [dbo].[UTENTI] ADD  CONSTRAINT [DF_UTENTI_ELIMINATO]  DEFAULT ((0)) FOR [ELIMINATO]
GO
ALTER TABLE [dbo].[UTENTI_PASSWORDS] ADD  DEFAULT ((0)) FOR [ELIMINATO]
GO
ALTER TABLE [dbo].[ARMADI_LAVATRICI]  WITH CHECK ADD  CONSTRAINT [FK_ARMADI_LAVATRICI_SEDIESAME] FOREIGN KEY([IDSEDE])
REFERENCES [dbo].[SEDIESAME] ([ID])
GO
ALTER TABLE [dbo].[ARMADI_LAVATRICI] CHECK CONSTRAINT [FK_ARMADI_LAVATRICI_SEDIESAME]
GO
ALTER TABLE [dbo].[CICLI]  WITH CHECK ADD  CONSTRAINT [FK_CICLI_DISPOSITIVI] FOREIGN KEY([IDDISPOSITIVO])
REFERENCES [dbo].[DISPOSITIVI] ([ID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[CICLI] CHECK CONSTRAINT [FK_CICLI_DISPOSITIVI]
GO
ALTER TABLE [dbo].[CICLI]  WITH CHECK ADD  CONSTRAINT [FK_CICLI_OPERATORI] FOREIGN KEY([IDOPERATOREESAME])
REFERENCES [dbo].[OPERATORI] ([ID])
GO
ALTER TABLE [dbo].[CICLI] CHECK CONSTRAINT [FK_CICLI_OPERATORI]
GO
ALTER TABLE [dbo].[CICLI]  WITH CHECK ADD  CONSTRAINT [FK_CICLI_STERILIZZATRICI] FOREIGN KEY([IDSTERILIZZATRICE])
REFERENCES [dbo].[ARMADI_LAVATRICI] ([ID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[CICLI] CHECK CONSTRAINT [FK_CICLI_STERILIZZATRICI]
GO
ALTER TABLE [dbo].[CICLIEXT]  WITH CHECK ADD  CONSTRAINT [FK_CICLIEXT_CICLI] FOREIGN KEY([IDCICLO])
REFERENCES [dbo].[CICLI] ([ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[CICLIEXT] CHECK CONSTRAINT [FK_CICLIEXT_CICLI]
GO
ALTER TABLE [dbo].[CICLISTATOLOG]  WITH CHECK ADD  CONSTRAINT [FK_CICLISTATOLOG_CICLI] FOREIGN KEY([IDCICLO])
REFERENCES [dbo].[CICLI] ([ID])
GO
ALTER TABLE [dbo].[CICLISTATOLOG] CHECK CONSTRAINT [FK_CICLISTATOLOG_CICLI]
GO
ALTER TABLE [dbo].[CICLISTATOLOG]  WITH CHECK ADD  CONSTRAINT [FK_CICLISTATOLOG_STATONEW] FOREIGN KEY([IDSTATONEW])
REFERENCES [dbo].[STATO] ([ID])
GO
ALTER TABLE [dbo].[CICLISTATOLOG] CHECK CONSTRAINT [FK_CICLISTATOLOG_STATONEW]
GO
ALTER TABLE [dbo].[CICLISTATOLOG]  WITH CHECK ADD  CONSTRAINT [FK_CICLISTATOLOG_STATOOLD] FOREIGN KEY([IDSTATOOLD])
REFERENCES [dbo].[STATO] ([ID])
GO
ALTER TABLE [dbo].[CICLISTATOLOG] CHECK CONSTRAINT [FK_CICLISTATOLOG_STATOOLD]
GO
ALTER TABLE [dbo].[DISPOSITIVI]  WITH CHECK ADD  CONSTRAINT [FK_DISPOSITIVI_FORNITORI] FOREIGN KEY([IDFORNITORE])
REFERENCES [dbo].[FORNITORI] ([ID])
GO
ALTER TABLE [dbo].[DISPOSITIVI] CHECK CONSTRAINT [FK_DISPOSITIVI_FORNITORI]
GO
ALTER TABLE [dbo].[DISPOSITIVI]  WITH CHECK ADD  CONSTRAINT [FK_DISPOSITIVI_SEDIESAME] FOREIGN KEY([IDSEDE])
REFERENCES [dbo].[SEDIESAME] ([ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[DISPOSITIVI] CHECK CONSTRAINT [FK_DISPOSITIVI_SEDIESAME]
GO
ALTER TABLE [dbo].[DISPOSITIVI]  WITH CHECK ADD  CONSTRAINT [FK_DISPOSITIVI_TIPIDISPOSITIVI] FOREIGN KEY([IDTIPO])
REFERENCES [dbo].[TIPIDISPOSITIVI] ([ID])
GO
ALTER TABLE [dbo].[DISPOSITIVI] CHECK CONSTRAINT [FK_DISPOSITIVI_TIPIDISPOSITIVI]
GO
ALTER TABLE [dbo].[LETTORI]  WITH CHECK ADD  CONSTRAINT [FK_LETTORI_SEDIESAME] FOREIGN KEY([IDSEDE])
REFERENCES [dbo].[SEDIESAME] ([ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[LETTORI] CHECK CONSTRAINT [FK_LETTORI_SEDIESAME]
GO
ALTER TABLE [dbo].[LETTORI]  WITH CHECK ADD  CONSTRAINT [FK_LETTORI_STATO] FOREIGN KEY([IDSTATODEFAULT])
REFERENCES [dbo].[STATO] ([ID])
GO
ALTER TABLE [dbo].[LETTORI] CHECK CONSTRAINT [FK_LETTORI_STATO]
GO
ALTER TABLE [dbo].[OPERATORI]  WITH CHECK ADD  CONSTRAINT [FK_OPERATORI_UTENTI] FOREIGN KEY([ID_UTENTE])
REFERENCES [dbo].[UTENTI] ([ID])
ON DELETE SET NULL
GO
ALTER TABLE [dbo].[OPERATORI] CHECK CONSTRAINT [FK_OPERATORI_UTENTI]
GO
ALTER TABLE [dbo].[OPERATORI_SEDI]  WITH CHECK ADD  CONSTRAINT [FK_OPERATORI_SEDI_OPERATORI] FOREIGN KEY([IDOPERATORE])
REFERENCES [dbo].[OPERATORI] ([ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[OPERATORI_SEDI] CHECK CONSTRAINT [FK_OPERATORI_SEDI_OPERATORI]
GO
ALTER TABLE [dbo].[OPERATORI_SEDI]  WITH CHECK ADD  CONSTRAINT [FK_OPERATORI_SEDI_SEDIESAME] FOREIGN KEY([IDSEDE])
REFERENCES [dbo].[SEDIESAME] ([ID])
GO
ALTER TABLE [dbo].[OPERATORI_SEDI] CHECK CONSTRAINT [FK_OPERATORI_SEDI_SEDIESAME]
GO
ALTER TABLE [dbo].[STATOCAMBIO]  WITH CHECK ADD  CONSTRAINT [FK_STATOCAMBIO_SEDIESAME] FOREIGN KEY([IDSEDE])
REFERENCES [dbo].[SEDIESAME] ([ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[STATOCAMBIO] CHECK CONSTRAINT [FK_STATOCAMBIO_SEDIESAME]
GO
ALTER TABLE [dbo].[STATOCAMBIO]  WITH CHECK ADD  CONSTRAINT [FK_STATOCAMBIO_STATONEW] FOREIGN KEY([IDSTATONEW])
REFERENCES [dbo].[STATO] ([ID])
GO
ALTER TABLE [dbo].[STATOCAMBIO] CHECK CONSTRAINT [FK_STATOCAMBIO_STATONEW]
GO
ALTER TABLE [dbo].[STATOCAMBIO]  WITH CHECK ADD  CONSTRAINT [FK_STATOCAMBIO_STATOOLD] FOREIGN KEY([IDSTATOOLD])
REFERENCES [dbo].[STATO] ([ID])
GO
ALTER TABLE [dbo].[STATOCAMBIO] CHECK CONSTRAINT [FK_STATOCAMBIO_STATOOLD]
GO
ALTER TABLE [dbo].[STERILIZZATRICIPARSING]  WITH CHECK ADD  CONSTRAINT [FK_STERILIZZATRICIPARSING_STERILIZZATRICI] FOREIGN KEY([IDSTERILIZZATRICE])
REFERENCES [dbo].[ARMADI_LAVATRICI] ([ID])
GO
ALTER TABLE [dbo].[STERILIZZATRICIPARSING] CHECK CONSTRAINT [FK_STERILIZZATRICIPARSING_STERILIZZATRICI]
GO
ALTER TABLE [dbo].[TIPIDISPOSITIVISTATOSCADENZA]  WITH CHECK ADD  CONSTRAINT [FK_TIPIDISPOSITIVISTATOSCADENZA_STATO1] FOREIGN KEY([IDSTATO])
REFERENCES [dbo].[STATO] ([ID])
GO
ALTER TABLE [dbo].[TIPIDISPOSITIVISTATOSCADENZA] CHECK CONSTRAINT [FK_TIPIDISPOSITIVISTATOSCADENZA_STATO1]
GO
ALTER TABLE [dbo].[TIPIDISPOSITIVISTATOSCADENZA]  WITH CHECK ADD  CONSTRAINT [FK_TIPIDISPOSITIVISTATOSCADENZA_STATO2] FOREIGN KEY([IDSTATODESTINAZIONE])
REFERENCES [dbo].[STATO] ([ID])
GO
ALTER TABLE [dbo].[TIPIDISPOSITIVISTATOSCADENZA] CHECK CONSTRAINT [FK_TIPIDISPOSITIVISTATOSCADENZA_STATO2]
GO
ALTER TABLE [dbo].[TIPIDISPOSITIVISTATOSCADENZA]  WITH CHECK ADD  CONSTRAINT [FK_TIPIDISPOSITIVISTATOSCADENZA_TIPIDISPOSITIVI] FOREIGN KEY([IDTIPODISPOSITIVO])
REFERENCES [dbo].[TIPIDISPOSITIVI] ([ID])
GO
ALTER TABLE [dbo].[TIPIDISPOSITIVISTATOSCADENZA] CHECK CONSTRAINT [FK_TIPIDISPOSITIVISTATOSCADENZA_TIPIDISPOSITIVI]
GO
ALTER TABLE [dbo].[UO_SEDI]  WITH CHECK ADD  CONSTRAINT [FK_UO_SEDI_SEDIESAME] FOREIGN KEY([IDSEDE])
REFERENCES [dbo].[SEDIESAME] ([ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[UO_SEDI] CHECK CONSTRAINT [FK_UO_SEDI_SEDIESAME]
GO
ALTER TABLE [dbo].[UO_SEDI]  WITH CHECK ADD  CONSTRAINT [FK_UO_SEDI_UO] FOREIGN KEY([IDUO])
REFERENCES [dbo].[UO] ([ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[UO_SEDI] CHECK CONSTRAINT [FK_UO_SEDI_UO]
GO
ALTER TABLE [dbo].[UTENTI]  WITH CHECK ADD  CONSTRAINT [FK_UTENTI_GRUPPI] FOREIGN KEY([ID_GRUPPO])
REFERENCES [dbo].[GRUPPI] ([ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[UTENTI] CHECK CONSTRAINT [FK_UTENTI_GRUPPI]
GO
ALTER TABLE [dbo].[UTENTI_SETTING]  WITH CHECK ADD  CONSTRAINT [FK_UTENTI_SETTING_UTENTI] FOREIGN KEY([IDUTENTE])
REFERENCES [dbo].[UTENTI] ([ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[UTENTI_SETTING] CHECK CONSTRAINT [FK_UTENTI_SETTING_UTENTI]
GO
/****** Object:  StoredProcedure [dbo].[SP_INSERTGROUP]    Script Date: 02/04/2021 05:19:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_INSERTGROUP]
(
	@GROUPID INT OUTPUT,
	@USERNAMEMOD VARCHAR(50),
	@COMPUTERNAME VARCHAR(50),
	@INSTALLATIONNAME VARCHAR(50),
	@GROUPNAME VARCHAR(50),
	@ALLOWEDACTION1 INT,
	@ALLOWEDACTION2 INT
)
AS
BEGIN TRANSACTION
	INSERT INTO GRUPPI (NOME, PERMESSI, PERMESSI2) VALUES (@GROUPNAME,@ALLOWEDACTION1,@ALLOWEDACTION2)
	SELECT @GROUPID = CAST(@@IDENTITY AS BIGINT)
COMMIT
GO
/****** Object:  StoredProcedure [dbo].[SP_INSERTUSER]    Script Date: 02/04/2021 05:19:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/****** Object:  StoredProcedure [dbo].[SP_INSERTUSER]    Script Date: 21/09/2020 12:17:29 ******/
CREATE PROCEDURE [dbo].[SP_INSERTUSER]
(
	@USERID INT OUTPUT,
	@USERNAMEMOD VARCHAR(50),
	@COMPUTERNAME VARCHAR(50),
	@INSTALLATIONNAME VARCHAR(50),
	@USERNAME VARCHAR(50),
	@FIRSTLOGIN BIT,
	@DISABLED BIT,
	@GROUPID INT,
	@DATECHANGEPWD VARCHAR(14),
	@DATELASTUSE VARCHAR(14)
)
AS
BEGIN TRANSACTION
	INSERT INTO UTENTI (USERNAME, PASSWORD, ID_GRUPPO, DISABILITATO, DATA_PASSWORD, DATA_ULTIMO_UTILIZZO, PRIMO_LOGIN) 
		VALUES (@USERNAME, '', @GROUPID, @DISABLED, @DATECHANGEPWD, @DATELASTUSE, @FIRSTLOGIN)
	SELECT @USERID = MAX(ID) FROM UTENTI
COMMIT

/****** Object:  StoredProcedure [dbo].[SP_MODIFYUSER]    Script Date: 21/09/2020 12:02:15 ******/
SET ANSI_NULLS ON
GO
/****** Object:  StoredProcedure [dbo].[SP_MODIFYGROUP]    Script Date: 02/04/2021 05:19:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_MODIFYGROUP]
(
	@USERNAMEMOD VARCHAR(50),
	@COMPUTERNAME VARCHAR(50),
	@INSTALLATIONNAME VARCHAR(50),
	@GROUPID INT,
	@GROUPNAME VARCHAR(50),
	@ALLOWEDACTION1 INT,
	@ALLOWEDACTION2 INT,
	@DELETED BIT
)
AS
BEGIN TRANSACTION

	DECLARE @DATE VARCHAR(14)
	SELECT @DATE = DATA FROM AM_GETSERVERDATE;

	DECLARE @VALOREOLD VARCHAR(1024)
	DECLARE @VALORENEW VARCHAR(1024)

	IF (@GROUPNAME IS NOT NULL)
	BEGIN
		UPDATE GRUPPI SET NOME = @GROUPNAME WHERE ID = @GROUPID
	END


	IF (@ALLOWEDACTION1 IS NOT NULL)
	BEGIN
		UPDATE GRUPPI SET PERMESSI = @ALLOWEDACTION1 WHERE ID = @GROUPID
	END

	IF (@ALLOWEDACTION2 IS NOT NULL)
	BEGIN
		UPDATE GRUPPI SET PERMESSI2 = @ALLOWEDACTION2 WHERE ID = @GROUPID
	END

	IF (@DELETED IS NOT NULL)
	BEGIN
		UPDATE GRUPPI SET ELIMINATO = @DELETED WHERE ID = @GROUPID
	END
COMMIT
GO
/****** Object:  StoredProcedure [dbo].[SP_MODIFYUSER]    Script Date: 02/04/2021 05:19:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_MODIFYUSER]
(
	@USERNAMEMOD VARCHAR(50),
	@COMPUTERNAME VARCHAR(50),
	@INSTALLATIONNAME VARCHAR(50),
	@USERID INT,
	@USERNAME VARCHAR(50),
	@SDESCRIZIONE VARCHAR(255),
	@PASSWORD VARCHAR(1024),
	@PASSWORDTYPE  INT,
	@GROUPID  INT,
	@DISABLED BIT,
	@PASSWORDDATE VARCHAR(14),
	@LASTUSEDATE VARCHAR(14),
	@FIRSTLOGIN BIT,
	@DELETED BIT,
	@CODE VARCHAR(50)
)
AS
BEGIN TRANSACTION
	IF (@USERNAME IS NOT NULL)
	BEGIN
		UPDATE UTENTI SET USERNAME = @USERNAME WHERE ID = @USERID;
	END

	IF (@SDESCRIZIONE IS NOT NULL)
	BEGIN
		UPDATE UTENTI SET DESCRIZIONE = @SDESCRIZIONE WHERE ID = @USERID;
	END

	IF (@PASSWORD IS NOT NULL)
	BEGIN
      	SET @PASSWORD = LTRIM(RTRIM(@PASSWORD)); -- PER COLPA DI ORACLE PASSO UNO SPAZIO QUANDO LA PASSWORD È DA RESETTARE --
		UPDATE UTENTI SET PASSWORD = @PASSWORD WHERE ID = @USERID
	END

	IF (@PASSWORDTYPE IS NOT NULL)
	BEGIN
		UPDATE UTENTI SET TIPO_PASSWORD = @PASSWORDTYPE WHERE ID = @USERID
	END

	IF (@GROUPID IS NOT NULL)
	BEGIN
		UPDATE UTENTI SET ID_GRUPPO = @GROUPID WHERE ID = @USERID
	END

	IF (@DISABLED IS NOT NULL)
	BEGIN
		UPDATE UTENTI SET DISABILITATO = @DISABLED WHERE ID = @USERID
	END

	IF (@PASSWORDDATE IS NOT NULL)
	BEGIN
		UPDATE UTENTI SET DATA_PASSWORD = @PASSWORDDATE WHERE ID = @USERID
	END

	IF (@LASTUSEDATE IS NOT NULL)
	BEGIN
		UPDATE UTENTI SET DATA_ULTIMO_UTILIZZO = @LASTUSEDATE WHERE ID = @USERID
	END

	IF (@FIRSTLOGIN IS NOT NULL)
	BEGIN
		UPDATE UTENTI SET PRIMO_LOGIN = @FIRSTLOGIN WHERE ID = @USERID
	END

	IF (@DELETED IS NOT NULL)
	BEGIN
		UPDATE UTENTI SET ELIMINATO = @DELETED WHERE ID = @USERID
	END

	IF (@CODE IS NOT NULL)
	BEGIN
		UPDATE UTENTI SET CODICEINTEGRAZIONE = @CODE WHERE ID = @USERID
	END
COMMIT
GO

/****** Object:  StoredProcedure [dbo].[SP_UPDATEDEVNEW]    Script Date: 02/04/2021 05:19:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_UPDATEDEVNEW] 
(
	@RES INT OUTPUT, 
	@TAGDEVICE VARCHAR(50), 
	@STATE INT, 
	@DATECLEAN VARCHAR(14), 
	@TAGUSERCLEAN VARCHAR(50), 
	@CLEANER INT, 
	@OLDSTATE INT, 
	@EXAM INT
)
AS
	DECLARE @CNT INT;
	DECLARE @IDCYCLE INT;
	DECLARE @IDTAG INT;
	DECLARE @IDUSERCLEAN INT;
	DECLARE @ID_STATO_INIZIO_CICLO INT;
BEGIN
	SELECT TOP(1) @ID_STATO_INIZIO_CICLO = ID FROM STATO WHERE INIZIOCICLO = 1

	SET @RES = -1;
	SELECT @CNT=COUNT(*) FROM DISPOSITIVI WHERE TAG=@TAGDEVICE
	IF (@CNT = 0)
	BEGIN
		SET @RES = -2;
		RETURN --IN CASO DI DEVICE NON TROVATO NON SI PROCEDE
	END
	
	SELECT @CNT=COUNT(*) FROM OPERATORI WHERE TAG=@TAGUSERCLEAN
	IF (@CNT = 0)
	BEGIN
		SET @RES = -3;
	END

	SELECT @IDTAG=ID FROM DISPOSITIVI WHERE TAG=@TAGDEVICE
	SELECT @IDUSERCLEAN=ID FROM OPERATORI WHERE TAG=@TAGUSERCLEAN

	IF (@STATE = 99999)
	BEGIN
		SELECT @IDCYCLE=MAX(ID) FROM CICLI WHERE IDDISPOSITIVO = @IDTAG
		UPDATE CICLI SET FAILED=1 WHERE ID=@IDCYCLE
		INSERT CICLI (IDDISPOSITIVO,DATAESAME,IDOPERATOREESAME,MODIFICAMANUALE,IDESAME)
			SELECT IDDISPOSITIVO,DATAESAME,IDOPERATOREESAME,MODIFICAMANUALE,IDESAME FROM CICLI WHERE ID=@IDCYCLE	  
		UPDATE DISPOSITIVI SET STATO = 2 WHERE ID = @IDTAG;
		SET @RES=@IDCYCLE;
		RETURN
	END
	IF (@STATE = @ID_STATO_INIZIO_CICLO) --SPORCO
	BEGIN
		SELECT @IDCYCLE=MAX(ID) FROM CICLI WHERE IDDISPOSITIVO = @IDTAG       
		INSERT CICLI (IDDISPOSITIVO,DATAESAME,IDOPERATOREESAME,IDESAME)
			VALUES (@IDTAG,@DATECLEAN,@IDUSERCLEAN,@EXAM)
		UPDATE DISPOSITIVI SET STATO = @STATE WHERE ID = @IDTAG;
		SELECT @IDCYCLE=MAX(ID) FROM CICLI WHERE IDDISPOSITIVO = @IDTAG
		INSERT INTO CICLISTATOLOG (IDCICLO, IDSTATOOLD, IDSTATONEW, IDOPERATORE, DATAORA) 
			VALUES (@IDCYCLE, @OLDSTATE, @STATE, @IDUSERCLEAN, @DATECLEAN)
		SET @RES=@IDCYCLE;
	END
END
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DIAGRAMPANE1', @value=N'[0E232FF0-B466-11CF-A24F-00AA00A3EFFF, 1.00]
BEGIN DESIGNPROPERTIES = 
   BEGIN PANECONFIGURATIONS = 
      BEGIN PANECONFIGURATION = 0
         NUMPANES = 4
         CONFIGURATION = "(H (1[40] 4[20] 2[20] 3) )"
      END
      BEGIN PANECONFIGURATION = 1
         NUMPANES = 3
         CONFIGURATION = "(H (1 [50] 4 [25] 3))"
      END
      BEGIN PANECONFIGURATION = 2
         NUMPANES = 3
         CONFIGURATION = "(H (1 [50] 2 [25] 3))"
      END
      BEGIN PANECONFIGURATION = 3
         NUMPANES = 3
         CONFIGURATION = "(H (4 [30] 2 [40] 3))"
      END
      BEGIN PANECONFIGURATION = 4
         NUMPANES = 2
         CONFIGURATION = "(H (1 [56] 3))"
      END
      BEGIN PANECONFIGURATION = 5
         NUMPANES = 2
         CONFIGURATION = "(H (2 [66] 3))"
      END
      BEGIN PANECONFIGURATION = 6
         NUMPANES = 2
         CONFIGURATION = "(H (4 [50] 3))"
      END
      BEGIN PANECONFIGURATION = 7
         NUMPANES = 1
         CONFIGURATION = "(V (3))"
      END
      BEGIN PANECONFIGURATION = 8
         NUMPANES = 3
         CONFIGURATION = "(H (1[56] 4[18] 2) )"
      END
      BEGIN PANECONFIGURATION = 9
         NUMPANES = 2
         CONFIGURATION = "(H (1 [75] 4))"
      END
      BEGIN PANECONFIGURATION = 10
         NUMPANES = 2
         CONFIGURATION = "(H (1[66] 2) )"
      END
      BEGIN PANECONFIGURATION = 11
         NUMPANES = 2
         CONFIGURATION = "(H (4 [60] 2))"
      END
      BEGIN PANECONFIGURATION = 12
         NUMPANES = 1
         CONFIGURATION = "(H (1) )"
      END
      BEGIN PANECONFIGURATION = 13
         NUMPANES = 1
         CONFIGURATION = "(V (4))"
      END
      BEGIN PANECONFIGURATION = 14
         NUMPANES = 1
         CONFIGURATION = "(V (2))"
      END
      ACTIVEPANECONFIG = 0
   END
   BEGIN DIAGRAMPANE = 
      BEGIN ORIGIN = 
         TOP = 0
         LEFT = 0
      END
      BEGIN TABLES = 
         BEGIN TABLE = "STATO"
            BEGIN EXTENT = 
               TOP = 73
               LEFT = 970
               BOTTOM = 203
               RIGHT = 1189
            END
            DISPLAYFLAGS = 280
            TOPCOLUMN = 0
         END
         BEGIN TABLE = "TIPIDISPOSITIVI"
            BEGIN EXTENT = 
               TOP = 138
               LEFT = 265
               BOTTOM = 234
               RIGHT = 455
            END
            DISPLAYFLAGS = 280
            TOPCOLUMN = 0
         END
         BEGIN TABLE = "DISPOSITIVI"
            BEGIN EXTENT = 
               TOP = 112
               LEFT = 621
               BOTTOM = 630
               RIGHT = 810
            END
            DISPLAYFLAGS = 280
            TOPCOLUMN = 0
         END
         BEGIN TABLE = "FORNITORI"
            BEGIN EXTENT = 
               TOP = 6
               LEFT = 265
               BOTTOM = 136
               RIGHT = 455
            END
            DISPLAYFLAGS = 280
            TOPCOLUMN = 0
         END
      END
   END
   BEGIN SQLPANE = 
   END
   BEGIN DATAPANE = 
      BEGIN PARAMETERDEFAULTS = ""
      END
   END
   BEGIN CRITERIAPANE = 
      BEGIN COLUMNWIDTHS = 11
         COLUMN = 1440
         ALIAS = 900
         TABLE = 1170
         OUTPUT = 720
         APPEND = 1400
         NEWVALUE = 1170
         SORTTYPE = 1350
         SORTORDER = 1410
         GROUPBY = 1350
         FILTER = 1350
         OR = 1350
         OR = 1350
         OR = 1350
      END
   END
END
' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'VISTADISPOSITIVI'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DIAGRAMPANECOUNT', @value=1 , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'VISTADISPOSITIVI'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DIAGRAMPANE1', @value=N'[0E232FF0-B466-11CF-A24F-00AA00A3EFFF, 1.00]
BEGIN DESIGNPROPERTIES = 
   BEGIN PANECONFIGURATIONS = 
	  BEGIN PANECONFIGURATION = 0
		 NUMPANES = 4
		 CONFIGURATION = "(H (1[40] 4[20] 2[20] 3) )"
	  END
	  BEGIN PANECONFIGURATION = 1
		 NUMPANES = 3
		 CONFIGURATION = "(H (1 [50] 4 [25] 3))"
	  END
	  BEGIN PANECONFIGURATION = 2
		 NUMPANES = 3
		 CONFIGURATION = "(H (1 [50] 2 [25] 3))"
	  END
	  BEGIN PANECONFIGURATION = 3
		 NUMPANES = 3
		 CONFIGURATION = "(H (4[30] 2[40] 3) )"
	  END
	  BEGIN PANECONFIGURATION = 4
		 NUMPANES = 2
		 CONFIGURATION = "(H (1 [56] 3))"
	  END
	  BEGIN PANECONFIGURATION = 5
		 NUMPANES = 2
		 CONFIGURATION = "(H (2[39] 3) )"
	  END
	  BEGIN PANECONFIGURATION = 6
		 NUMPANES = 2
		 CONFIGURATION = "(H (4 [50] 3))"
	  END
	  BEGIN PANECONFIGURATION = 7
		 NUMPANES = 1
		 CONFIGURATION = "(V (3))"
	  END
	  BEGIN PANECONFIGURATION = 8
		 NUMPANES = 3
		 CONFIGURATION = "(H (1[56] 4[18] 2) )"
	  END
	  BEGIN PANECONFIGURATION = 9
		 NUMPANES = 2
		 CONFIGURATION = "(H (1 [75] 4))"
	  END
	  BEGIN PANECONFIGURATION = 10
		 NUMPANES = 2
		 CONFIGURATION = "(H (1[66] 2) )"
	  END
	  BEGIN PANECONFIGURATION = 11
		 NUMPANES = 2
		 CONFIGURATION = "(H (4 [60] 2))"
	  END
	  BEGIN PANECONFIGURATION = 12
		 NUMPANES = 1
		 CONFIGURATION = "(H (1) )"
	  END
	  BEGIN PANECONFIGURATION = 13
		 NUMPANES = 1
		 CONFIGURATION = "(V (4))"
	  END
	  BEGIN PANECONFIGURATION = 14
		 NUMPANES = 1
		 CONFIGURATION = "(V (2))"
	  END
	  ACTIVEPANECONFIG = 5
   END
   BEGIN DIAGRAMPANE = 
	  PANEHIDDEN = 
	  BEGIN ORIGIN = 
		 TOP = 0
		 LEFT = 0
	  END
	  BEGIN TABLES = 
		 BEGIN TABLE = "DISPOSITIVI"
			BEGIN EXTENT = 
			   TOP = 6
			   LEFT = 38
			   BOTTOM = 136
			   RIGHT = 238
			END
			DISPLAYFLAGS = 280
			TOPCOLUMN = 0
		 END
		 BEGIN TABLE = "TIPIDISPOSITIVISTATOSCADENZA"
			BEGIN EXTENT = 
			   TOP = 6
			   LEFT = 276
			   BOTTOM = 136
			   RIGHT = 470
			END
			DISPLAYFLAGS = 280
			TOPCOLUMN = 0
		 END
	  END
   END
   BEGIN SQLPANE = 
   END
   BEGIN DATAPANE = 
	  BEGIN PARAMETERDEFAULTS = ""
	  END
	  BEGIN COLUMNWIDTHS = 9
		 WIDTH = 284
		 WIDTH = 1500
		 WIDTH = 1500
		 WIDTH = 1500
		 WIDTH = 1500
		 WIDTH = 1500
		 WIDTH = 1500
		 WIDTH = 1500
		 WIDTH = 1500
	  END
   END
   BEGIN CRITERIAPANE = 
	  PANEHIDDEN = 
	  BEGIN COLUMNWIDTHS = 11
		 COLUMN = 1440
		 ALIAS = 900
		 TABLE = 1170
		 OUTPUT = 720
		 APPEND = 1400
		 NEWVALUE = 1170
		 SORTTYPE = 1350
		 SORTORDER = 1410
		 GROUPBY = 1350
		 FILTER = 1350
		 OR = 1350
		 OR = 1350
		 OR = 1350
	  END
   END
END
' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'VISTADISPOSITIVISCADUTI'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DIAGRAMPANECOUNT', @value=1 , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'VISTADISPOSITIVISCADUTI'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DIAGRAMPANE1', @value=N'[0E232FF0-B466-11CF-A24F-00AA00A3EFFF, 1.00]
BEGIN DESIGNPROPERTIES = 
   BEGIN PANECONFIGURATIONS = 
      BEGIN PANECONFIGURATION = 0
         NUMPANES = 4
         CONFIGURATION = "(H (1[40] 4[20] 2[20] 3) )"
      END
      BEGIN PANECONFIGURATION = 1
         NUMPANES = 3
         CONFIGURATION = "(H (1 [50] 4 [25] 3))"
      END
      BEGIN PANECONFIGURATION = 2
         NUMPANES = 3
         CONFIGURATION = "(H (1 [50] 2 [25] 3))"
      END
      BEGIN PANECONFIGURATION = 3
         NUMPANES = 3
         CONFIGURATION = "(H (4 [30] 2 [40] 3))"
      END
      BEGIN PANECONFIGURATION = 4
         NUMPANES = 2
         CONFIGURATION = "(H (1 [56] 3))"
      END
      BEGIN PANECONFIGURATION = 5
         NUMPANES = 2
         CONFIGURATION = "(H (2 [66] 3))"
      END
      BEGIN PANECONFIGURATION = 6
         NUMPANES = 2
         CONFIGURATION = "(H (4 [50] 3))"
      END
      BEGIN PANECONFIGURATION = 7
         NUMPANES = 1
         CONFIGURATION = "(V (3))"
      END
      BEGIN PANECONFIGURATION = 8
         NUMPANES = 3
         CONFIGURATION = "(H (1[56] 4[18] 2) )"
      END
      BEGIN PANECONFIGURATION = 9
         NUMPANES = 2
         CONFIGURATION = "(H (1 [75] 4))"
      END
      BEGIN PANECONFIGURATION = 10
         NUMPANES = 2
         CONFIGURATION = "(H (1[66] 2) )"
      END
      BEGIN PANECONFIGURATION = 11
         NUMPANES = 2
         CONFIGURATION = "(H (4 [60] 2))"
      END
      BEGIN PANECONFIGURATION = 12
         NUMPANES = 1
         CONFIGURATION = "(H (1) )"
      END
      BEGIN PANECONFIGURATION = 13
         NUMPANES = 1
         CONFIGURATION = "(V (4))"
      END
      BEGIN PANECONFIGURATION = 14
         NUMPANES = 1
         CONFIGURATION = "(V (2))"
      END
      ACTIVEPANECONFIG = 0
   END
   BEGIN DIAGRAMPANE = 
      BEGIN ORIGIN = 
         TOP = 0
         LEFT = 0
      END
      BEGIN TABLES = 
         BEGIN TABLE = "A"
            BEGIN EXTENT = 
               TOP = 6
               LEFT = 266
               BOTTOM = 453
               RIGHT = 456
            END
            DISPLAYFLAGS = 280
            TOPCOLUMN = 0
         END
         BEGIN TABLE = "VISTADISPOSITIVI"
            BEGIN EXTENT = 
               TOP = 6
               LEFT = 38
               BOTTOM = 381
               RIGHT = 228
            END
            DISPLAYFLAGS = 280
            TOPCOLUMN = 0
         END
      END
   END
   BEGIN SQLPANE = 
   END
   BEGIN DATAPANE = 
      BEGIN PARAMETERDEFAULTS = ""
      END
   END
   BEGIN CRITERIAPANE = 
      BEGIN COLUMNWIDTHS = 11
         COLUMN = 1440
         ALIAS = 900
         TABLE = 3375
         OUTPUT = 720
         APPEND = 1400
         NEWVALUE = 1170
         SORTTYPE = 1350
         SORTORDER = 1410
         GROUPBY = 1350
         FILTER = 1350
         OR = 1350
         OR = 1350
         OR = 1350
      END
   END
END
' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'VISTADISPOSITIVIULTIMOCICLO'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DIAGRAMPANECOUNT', @value=1 , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'VISTADISPOSITIVIULTIMOCICLO'
GO
USE [master]
GO
ALTER DATABASE [CLEANTRACK] SET  READ_WRITE 
GO
