USE CLEANTRACK
GO

INSERT INTO UTENTI (USERNAME, [PASSWORD], DESCRIZIONE, ID_GRUPPO, DISABILITATO, SCADENZA_PASSWORD, DATA_PASSWORD, DATA_ULTIMO_UTILIZZO, PRIMO_LOGIN, TIPO_PASSWORD)
VALUES 
('CANTEL',
'cantel',
'',
(SELECT ID FROM GRUPPI WHERE NOME = 'ADMINISTRATORS'),
0,
9999,
(SELECT REPLACE(CONVERT(VARCHAR, GETDATE(),23),'-','') + REPLACE(CONVERT(VARCHAR, GETDATE(),108),':','')),
(SELECT REPLACE(CONVERT(VARCHAR, GETDATE(),23),'-','') + REPLACE(CONVERT(VARCHAR, GETDATE(),108),':','')),
0,
0);
GO

INSERT INTO GRUPPI (NOME, DESCRIZIONE, PERMESSI, PERMESSI2) VALUES ('OPERATORI', 'OPERATORI', 0, 0);
GO